Fdy/enhance copy
DeepLink-org/deeplink.framework pull request #430
Opened 2023-11-15 10:37 UTC by fandaoyi

问题：
diopiCopy api 要求有多种能力， vendor 不一定能全部实现（比如遂原只实现了少部分能力），目前的逻辑是要么报错， 要么全部回退到 缓慢的基于cpu的copy （除了direct copy）。我们希望能使用 diopiCopy 提高性能， 但是又要能更灵活的处理不能被支持的case。
1. 合并原来的 dipuCopy 逻辑， 提供一定的可定制性。 vendor 可以使用/部分使用 diopiCopy  来处理 设备上的copy操作。 其他copy （d2h 等）默认会自动处理。
2. . 将 d2h， h2d， between device 等copy 逻辑优先分派到 设备上执行（如果 diopi copy 可用）以提高性能。

2023-11-20 09:49 UTC, zhaoguochun1995 commented on dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
> +  interface: diopiCopyInp(ctx, srcTemp, self)
diopiCopyInp 接口的语义一定要是清晰明确的，不能在不同设备上有不同的语义。如果不同设备在不同设备上实现的能力不一致，对上层调用者来说，很难保证跨平台跨设备调用。除非是设备实在难以实现的，这种情况需要从diopiCopyInp剥离出来。diopi接口设计的初衷就是为了跨设备、跨框架。不知我的理解是否有问题？

2023-11-20 11:28 UTC, fandaoyi commented on dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
> +  interface: diopiCopyInp(ctx, srcTemp, self)
目前DipuCopy 的默认实现也是假设 diopi_copy 可以处理全部的device copy。 但是实际遇到的问题是，比如遂原至今没有实现完整的 diopi_copy， 但他依然有优化 部分case的需求。所以我们也提供给用户渐进执行的能力。我觉得接口的语义清晰和 允许部分实现这两个事并不矛盾。

2023-11-20 11:45 UTC, mrdanielw commented on dipu/torch_dipu/csrc_dipu/aten/DIPUATenFunctions.h
> -  static at::Tensor &copy_(at::Tensor &self, const at::Tensor &src,
diopi_function.yaml里面的 copy_之前和现在都在  为啥这次要删掉？

2023-11-20 11:57 UTC, mrdanielw commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.h
> +  } else if (src.device().index() != dst.device().index()) {
这个else 不加调理更清晰点？

2023-11-20 12:07 UTC, mrdanielw commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +#pragma once
为啥有俩一样的文件  DIPUCopy.hpp 和  DIPUCopy.h?

2023-11-21 04:12 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/DIPUATenFunctions.h
> -  static at::Tensor &copy_(at::Tensor &self, const at::Tensor &src,
这是最老的代码，现在不走这个

2023-11-21 04:13 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +#pragma once
提错了。 已经删了 .h

2023-11-21 04:20 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.h
> +  } else if (src.device().index() != dst.device().index()) {
fix

2023-11-21 07:31 UTC, mrdanielw approved these changes

2023-11-22 08:20 UTC, lljbash requested changes

2023-11-22 08:20 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +template <bool DiopiCopy, bool DiopiCast>
1. 想办法提高模板参数可读性
2. 考虑放到 cpp 里，用前向声明显式实例化

2023-11-22 11:44 UTC, caikun-pjlab commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +                      info.copyType_ != DIPUCopyType::D2Self);
if 分支直接return，不需要else分支了，降低嵌套深度

2023-11-22 11:44 UTC, caikun-pjlab commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +      auto sameAsSrc = at::empty(src.sizes(), src.options().device(newDevice),
这个分支为什么不需要处理willBackfillSrc参数呢？

2023-11-22 11:50 UTC, caikun-pjlab commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +// Copyright (c) 2023, DeepLink.
能否补充一个性能测试，说明性能优化效果

2023-11-22 11:51 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +      auto sameAsSrc = at::empty(src.sizes(), src.options().device(newDevice),
只有有空洞的case 才要回填。

2023-11-22 11:53 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +// Copyright (c) 2023, DeepLink.
性能的后面再说？ 现在那个 benchmark 测例的配置有问题， 没有基准，也没法指定 设备 对应的性能。  之前 camb cuda上都是手动改数。

2023-11-22 11:53 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +// Copyright (c) 2023, DeepLink.
我把fix的 bug补下测例吧， 现在还有个bug

2023-11-22 13:34 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +                      info.copyType_ != DIPUCopyType::D2Self);
没太理解，是说下面的 else 删掉？ 我感觉留给编译器去优化比较好？ 这样规整些， 其他地方也是这样的逻辑

2023-11-23 04:11 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +template <bool DiopiCopy, bool DiopiCast>
简单改吧， 我重命名了下

2023-11-23 04:12 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +template <bool DiopiCopy, bool DiopiCast>
DIPUCopyInpOnCPU 和 DIPUCopyInpOnDIOPI

2023-11-23 04:32 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctions.hpp
>    return std::tie(grad_input, grad_weight, grad_bias);
没太理解， 你期望的行为是啥？ 用 move吗？

2023-11-24 02:24 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctions.hpp
>    return std::tie(grad_input, grad_weight, grad_bias);
make tuple 或者直接中括号括起来吧，tie 设计出来不是这个用途
https://stackoverflow.com/questions/72657145/returning-a-stdtie-dangling-reference

2023-11-24 02:33 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctions.hpp
>    return std::tie(grad_input, grad_weight, grad_bias);
他们应该抄的pytorch的。

2023-11-24 02:36 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +                      info.copyType_ != DIPUCopyType::D2Self);
@fandaoyi 现在主流确实是建议 early return 的。

2023-11-24 08:25 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/vendor/camb/CambCopyInplace.cpp
> +static int32_t cuda_init = []() {
这个初始化顺序还是要仔细确认一下吧，而且这样写真的好奇怪

2023-11-27 06:20 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +                      info.copyType_ != DIPUCopyType::D2Self);
> if 分支直接return，不需要else分支了，降低嵌套深度

那我统一改下吧

2023-11-27 06:25 UTC, caikun-pjlab approved these changes

2023-11-27 06:25 UTC, caikun-pjlab commented on dipu/tests/python/unittests/test_copy.py
> +      t1 = torch.ones((6, 4), device=device)
t1全是1，没法测试正确性吧；可以使用torch.arange(0, 24).reshape(6, 4).cuda()生成确定的输入，然后校验返回值

2023-11-27 07:05 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +  H2D,
我加个注释吧， 全称太长了

2023-11-27 11:15 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/vendor/camb/CambCopyInplace.cpp
> +static int32_t cuda_init = []() {
从目前的代码看， 初始地址在编译时就赋值了。不存在竞争。 具体的待凌劼看下有否相关标准。暂时保持目前的行为。

2023-11-27 12:40 UTC, lljbash approved these changes
lgtm

2023-11-27 14:39 UTC, merged