[dicp][tops]:Fix some ops.
DeepLink-org/deeplink.framework pull request #431
Opened 2023-11-16 03:29 UTC by Reinerzhou

2023-11-16 03:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DeepLink-org/deeplink.framework?pullRequest=431) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DeepLink-org/deeplink.framework?pullRequest=431) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DeepLink-org/deeplink.framework?pullRequest=431) it.</sub>

2023-11-17 09:30 UTC, jinminxi104 requested changes

2023-11-17 09:50 UTC, Reinerzhou commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +                pass
llama_finetune中的bmm参数都是f16，不转为f32计算精度错误。

2023-11-17 09:50 UTC, Reinerzhou commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +        return self.get_proxy(tops_op.Gemm, args, kwargs)
已改为在conversion处转换。

2023-11-17 09:50 UTC, Reinerzhou commented on dicp/dicp/vendor/TopsGraph/codegen/enflame.py
> +                call_body.writeline(f'del {arg}')
args，bufs分别为输入，输出参数的变量名列表，428行的if self.output_args[i] not in self.input_args:判断输出跟输入相同的话不需要额外去调用gen_empty_tensor；然后这个bufs要在return处使用，因此return之前对args进行del的时候需要判断下。

2023-11-17 09:50 UTC, Reinerzhou commented on dicp/dicp/vendor/TopsGraph/codegen/enflame.py
> +        return src_code
已删除。

2023-11-17 13:33 UTC, jinminxi104 commented
@CyCle1024 PTAL
特别是dot,mm,dot_general的部分

2023-11-17 13:46 UTC, CyCle1024 commented
@Reinerzhou @jinminxi104 本PR中含有大量将原本正确的内容改回错误状态的修改，无法一一指出，建议 @Reinerzhou 与 @yao-fengchen 了解详情

2023-11-17 13:56 UTC, CyCle1024 requested changes
@Reinerzhou @jinminxi104 本PR中含有许多将原本正确的内容改回错误状态的修改，主要涉及 Dot Gemm Bmm；建议 @Reinerzhou 与 @yao-fengchen 了解详情，tops后端设计中应该不包含 Bmm 这样的算子（目前尚未去除），只在 Conversion 中将 Bmm 转向了 DotGeneral，aten.dot的语义是两个一维向量的内积，详见https://pytorch.org/docs/stable/generated/torch.dot.html#torch.dot

2023-11-17 14:03 UTC, jinminxi104 requested changes

2023-11-17 14:03 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +    def Pow_Tensor_Scalar(self, *args, **kwargs):
这两个pow最后到codegen也是同一个pow？那就没必要分开了

2023-11-17 14:05 UTC, jinminxi104 commented
@CyCle1024 
aten.dot -> tops.dot
aten.mm -> tops.dot_general
aten.bmm -> tops.dot_general
对吗？

2023-11-17 14:12 UTC, CyCle1024 commented
> @CyCle1024 aten.dot -> tops.dot aten.mm -> tops.dot_general aten.bmm -> tops.dot_general 对吗？

首先没有aten.dot，过去的代码中错误地将tops dot 与 aten.dot关联在一起，fengchen改掉了。主要的就是
aten.mm -> tops dot (也可以是dot general，但是语义上 aten.mm就是yops dot)
aten.bmm-> tops dot_general

2023-11-17 14:31 UTC, Reinerzhou commented
> > @CyCle1024 aten.dot -> tops.dot aten.mm -> tops.dot_general aten.bmm -> tops.dot_general 对吗？
> 
> 首先没有aten.dot，过去的代码中错误地将tops dot 与 aten.dot关联在一起，fengchen改掉了。主要的就是 aten.mm -> tops dot (也可以是dot general，但是语义上 aten.mm就是tops dot) aten.bmm-> tops dot_general



> > @CyCle1024 aten.dot -> tops.dot aten.mm -> tops.dot_general aten.bmm -> tops.dot_general 对吗？
> 
> 首先没有aten.dot，过去的代码中错误地将tops dot 与 aten.dot关联在一起，fengchen改掉了。主要的就是 aten.mm -> tops dot (也可以是dot general，但是语义上 aten.mm就是tops dot) aten.bmm-> tops dot_general

试了下确实没有aten.dot的；所以enflame.py里面应该只有dot和dotgenal（目前多了bmm），conversion部分把mm，bmm分别作转换到dot， dotgeneral；我找时间改好

2023-11-17 14:31 UTC, Reinerzhou commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +    def Pow_Tensor_Scalar(self, *args, **kwargs):
好的

2023-11-20 07:53 UTC, CyCle1024 approved these changes

2023-11-20 08:05 UTC, jinminxi104 approved these changes

2023-11-20 08:11 UTC, merged