[dicp] Run llama_finetune success.
DeepLink-org/deeplink.framework pull request #440
Opened 2023-11-20 08:58 UTC by Reinerzhou

2023-11-22 15:43 UTC, jinminxi104 requested changes

2023-11-22 15:43 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/codegen/enflame.py
> +            func_body.writeline(f'input_ptrs.emplace_back(inputs_ptr[{str(i)}]);')
为什么去除了static cast？

2023-11-22 15:43 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/codegen/enflame.py
> +                func_body.writeline(f'output_ptrs.emplace_back(outputs_ptr[{output_ptr_count}]);')
和input的地方一样加上static cast是不是比较好？

2023-11-22 15:43 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/codegen/enflame.py
> +            self.empty_output = True
整体上，empty_output和inplace_args没有必然联系吧？

2023-11-23 07:19 UTC, CyCle1024 approved these changes

2023-11-23 09:19 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/codegen/enflame.py
> +            func_body.writeline(f'input_ptrs.emplace_back(inputs_ptr[{str(i)}]);')
c函数入口就是void*

2023-11-23 09:20 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/codegen/enflame.py
> +                func_body.writeline(f'output_ptrs.emplace_back(outputs_ptr[{output_ptr_count}]);')
c函数入口处已经处理为void*

2023-12-04 07:40 UTC, jinminxi104 approved these changes

2023-12-04 07:42 UTC, merged