[dipu] update tidy configuration and remove if-constexpr in C++14
DeepLink-org/deeplink.framework pull request #470
Opened 2023-11-28 10:19 UTC by wiryls

This PR includes two changes:

1. update tidy configuration `bugprone-signed-char-misuse.CharTypdefsToIgnore`;
2. remove if-constexpr as current C++ version is 14.

2023-11-29 03:29 UTC, lljbash requested changes

2023-11-29 03:29 UTC, lljbash commented on dipu/.clang-tidy
> +    value: 'int8_t'
确认加上这个就足够了吗

2023-11-29 03:29 UTC, lljbash commented on dipu/.clangd
> +  MissingIncludes: Strict
这个现在加的话影响太大了吧，最好先用 iwyu 跑一遍 fix

2023-11-29 03:29 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/collection.cpp
> +    time_t operator()(ExtraFields<Event::OutOfMemory> const& i) const {
const 放前面，保持风格一致？

2023-11-29 03:29 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/collection.cpp
> +  struct TimeGetter {
这里匿名会不会方便提示后面有个现场定义的变量

2023-11-29 03:29 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/collection.cpp
> +    std::reference_wrapper<decltype(converter)> convert;
考虑加个空行或者调到最前面，我一下找不到成员变量在哪里

2023-11-29 03:29 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/collection.cpp
> +  } start_time_of{std::ref(converter)};
考虑在某处加一行简单的注释，说明这个 function like 对象的作用

2023-11-29 06:24 UTC, lljbash commented on dipu/.clang-tidy
> +    value: 'int8_t'
我们昨天报的那个不是 alias 成别的了，受不受影响？

2023-11-29 06:24 UTC, lljbash commented on dipu/.clangd
> +  MissingIncludes: Strict
我这里会满屏报错啊，虽然我可以随手修

2023-11-29 07:50 UTC, caikun-pjlab commented on dipu/torch_dipu/csrc_dipu/profiler/collection.cpp
> +  struct {
看起来跟原始逻辑能力上不等价，原始逻辑是 EventType::Backend 和 其他；start_time_of没有体现其他的EventType，只包含了 Event::Backend 和 Event::OutOfMemory

2023-11-29 09:31 UTC, caikun-pjlab approved these changes

2023-11-29 10:55 UTC, lljbash commented on dipu/.clang-tidy
> +    value: 'int8_t'
按我的理解应该加上 DeviceIndex

2023-11-30 04:08 UTC, lljbash commented on dipu/.clang-tidy
> +    value: 'int8_t'
> 试了一下，你说得对。另外我发现它还是字符串匹配，这里只加 `c10::DeviceIndex` 就够，还是再加上 `DeviceIndex`？

c10::DeviceIndex，代码里没有任何道理省略 c10

2023-12-01 09:17 UTC, merged