[dipu] Fix warning based on the results of clang-tidy
DeepLink-org/deeplink.framework pull request #509
Opened 2023-12-08 05:50 UTC by lwysense

2023-12-11 13:23 UTC, lljbash requested changes
看了一半，建议再跑一下 tidy

2023-12-11 13:23 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +// NOLINTBEGIN: These should not be const variables
check 名

2023-12-11 13:23 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +// NOLINTBEGIN: These should not be const variables
看起来注释也不对

2023-12-11 13:23 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +  // NOLINTBEGIN: These should not be const variables
ditto

2023-12-11 13:23 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctions.hpp
> +  out_cpu = at::silu_out(self_cpu, out_cpu);  // NOLINT: It's the correct order
check 名

2023-12-11 13:23 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/EmptyOpsKernel.cpp
> -using c10::TensorImpl;
能不能都不要了，该改的改一下

2023-12-11 13:23 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/StorageShapeKernel.cpp
>  using dipu::devproxy::current_device;
ditto

2023-12-11 13:23 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp
> +static constexpr size_t kMega = static_cast<const size_t>(1024 * 1024);
auto
不然估计过不了tidy

2023-12-11 13:23 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp
> +                   // NOLINTNEXTLINE(performance-no-int-to-ptr)
是这个错吗

2023-12-11 13:23 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp
> +            return reinterpret_cast<uint64_t>(stream.rawstream());
这里也会报呀

2023-12-12 03:49 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/base/DIPUGlobals.cpp
> +  if (called) {
这里我以前问过，他就没考虑线程安全，也不知道为什么要搞个 atomic

2023-12-15 07:47 UTC, lwysense commented on dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp
> +                   // NOLINTNEXTLINE(performance-no-int-to-ptr)
是这个warning

2023-12-15 07:48 UTC, lwysense commented on dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp
> +            return reinterpret_cast<uint64_t>(stream.rawstream());
看起来，这个cast和上一个cast是一个相反的cast，确实没有报warning

2023-12-18 03:41 UTC, lljbash requested changes

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +static std::vector<std::string> getFallbackList() {
把它们放到 dipu 的匿名 ns 里去

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctions.hpp
> +  out_cpu = at::silu_out(self_cpu, out_cpu);
那个注释咋删了

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctionsForAmpGradScaler.cpp
> +    // NOLINTNEXTLINE:const_cast here is safe according to pytorch's source code
帮我加个 check 类型

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
>  static std::string _allclose(const at::Tensor& a, const at::Tensor& b) {
这里有没有性能问题？@wiryls 记录一下

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/binding/DIPUpybind.h
> +  THPDtype dtype;  // NOLINT(cppcoreguidelines-pro-type-member-init)
试试空大括号初始化

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp
> +                   // NOLINTNEXTLINE(performance-no-int-to-ptr)
这里需要讨论一下是怎么回事@wiryls ，搞清楚以后补个文档

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/binding/ExportTensor.cpp
> +static std::array<PyObject*, 2> splitArgs(PyObject* args) {
这个函数不对了吧，相当于返回局部变量的指针？

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/diopirt/diopi_helper.cpp
> +  if (!tensor.has_value()) {
> 考虑直接写为 `not tensor`，不需要 `has_value`

这里无所谓的

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/collection.cpp
> +  constexpr time_t ns_per_us = 1000;
```suggestion
  constexpr time_t kNsPerUs = 1000;
```

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/collection.cpp
> +  constexpr time_t ns_per_us = 1000;
尽量靠近使用处

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/collection.cpp
> +    constexpr size_t ns_per_us = 1000;
ditto

2023-12-18 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/collection.cpp
> +  constexpr time_t ns_per_us = 1000;
ditto

2023-12-18 03:42 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
>        stream >> line;
> 直接使用 `>>` 可能存在风险？如果 op 的名称是普通的字母及数字还行，但一旦混入一些奇怪的字符，比如换行、空就会导致结果不太对

op 不会有这些东西
不过我也觉得强制要求换行好

2023-12-18 09:10 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
>  static std::string _allclose(const at::Tensor& a, const at::Tensor& b) {
> 是说哪个方面，try-catch 导致的性能下降么，还是说这里的实现不够好。另外我也不太明白，为啥返回字符串。

就是字符串

2023-12-22 02:05 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +static std::vector<std::string> getFallbackList() {
> 已经用static修饰了，还需要放到一个匿名空间中吗

现在在全局，起码丢到 dipu 里面去。

匿名空间是 preferred over static

2023-12-25 10:44 UTC, lwysense commented on dipu/torch_dipu/csrc_dipu/binding/ExportTensor.cpp
> +static std::shared_ptr<PyObject* [2]> splitArgs(PyObject* args) {
> 看到注释，似乎还在讨论如何修改，这次不方便改就不管这个评论了吧

嗯嗯，加了todo，后续由道毅修改

2023-12-26 01:45 UTC, lljbash approved these changes

2023-12-26 01:45 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/CustomFallbackFunctions.hpp
> +  // NOLINTNEXTLINE(readability-suspicious-call-argument):It's the correct order
```suggestion
  // NOLINTNEXTLINE(readability-suspicious-call-argument): It's the correct order
```

2023-12-26 02:55 UTC, merged