clang-tidy_shanhang
DeepLink-org/deeplink.framework pull request #516
Opened 2023-12-08 09:38 UTC by ustclight-sls

2023-12-08 09:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DeepLink-org/deeplink.framework?pullRequest=516) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/DeepLink-org/deeplink.framework?pullRequest=516) before we can accept your contribution.<br/>**17** out of **18** committers have signed the CLA.<br/><br/>:white_check_mark: KevinfromTJ<br/>:white_check_mark: MiaoYYu<br/>:white_check_mark: wugeshui<br/>:white_check_mark: yao-fengchen<br/>:white_check_mark: yewentao256<br/>:white_check_mark: fandaoyi<br/>:white_check_mark: wiryls<br/>:white_check_mark: hellozmz<br/>:white_check_mark: tangzhiyi11<br/>:white_check_mark: wyz5864<br/>:white_check_mark: jingguo-st<br/>:white_check_mark: caikun-pjlab<br/>:white_check_mark: liwenjian-sensetime<br/>:white_check_mark: lljbash<br/>:white_check_mark: Wrench-Git<br/>:white_check_mark: Reinerzhou<br/>:white_check_mark: POI-WX<br/>:x: shanhang<br/><hr/>**shanhang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DeepLink-org/deeplink.framework?pullRequest=516) it.</sub>

2023-12-11 04:45 UTC, lljbash commented
这个commit历史为什么这么混乱

2023-12-11 05:03 UTC, lljbash requested changes

2023-12-11 05:03 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +DIPU_REGISTER_ALLOCATOR(BF, CPU, BFCachingAllocator, 0);
这俩是哪来的

2023-12-11 05:03 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPURawCachingAllocator.cpp
> +      const int bytes_num = 512;
ditto

2023-12-11 07:10 UTC, ustclight-sls commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +DIPU_REGISTER_ALLOCATOR(BF, CPU, BFCachingAllocator, 0);
const auto DIPU_DEVICE_TYPE = at::DeviceType::DIPU_DEVICE_TYPE_MACRO;

2023-12-11 09:06 UTC, ustclight-sls commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStream.cpp
> +DIPUStream getDIPUStreamFromPool(c10::DeviceIndex device) {
.h文件里原来写代码的人这样定义的

2023-12-12 03:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBSCachingAllocator.cpp
>          std::deque<DIPUEvent> events;
可以 reserve 一下

2023-12-12 06:35 UTC, ustclight-sls commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStream.cpp
> +DIPUStream getDIPUStreamFromPool(c10::DeviceIndex device) {
我已经都改成device_index了

2023-12-12 09:19 UTC, ustclight-sls commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBSCachingAllocator.cpp
> +  BSCachingAllocator() { impl = std::make_unique<Impl>(); }
未提示，可能是版本差异

2023-12-12 09:34 UTC, lljbash reviewed
format 还是没跑

2023-12-12 09:34 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStream.cpp
> +  current_streams = std::make_unique<std::vector<c10::StreamId>>(num_dipus);
这坨东西先别管他了，之后初始化的东西要全部一起看一下

2023-12-12 09:34 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +DIPU_REGISTER_ALLOCATOR(BF, CPU, BFCachingAllocator, 0);
为什么现在这样可以啊

2023-12-12 11:33 UTC, ustclight-sls commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +DIPU_REGISTER_ALLOCATOR(BF, CPU, BFCachingAllocator, 0);
应该是将原来::形式的参数识别为namespace名了，但这个版本不支持这个格式，需要传一个不含::的串去里面拼接，同时.h里面的device_type手动补充at::DeviceType

2023-12-13 02:54 UTC, lljbash approved these changes

2023-12-13 06:42 UTC, fandaoyi approved these changes

2023-12-13 06:43 UTC, mrdanielw approved these changes

2023-12-13 06:52 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBSCachingAllocator.cpp
>          std::deque<DIPUEvent> events;
我觉得可以用空的， 因为 stream 大多数情况也是空的。 多的也不过1,2 个， 预先分配反倒有点 ‘过’？

2023-12-13 06:54 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStream.cpp
> +  deviceId_t devidx_{};
经讨论， 留给 @wiryls  修改。

2023-12-13 06:56 UTC, merged