Cjt/infer op resinfo
DeepLink-org/deeplink.framework pull request #517
Opened 2023-12-08 11:13 UTC by KevinfromTJ

- add op view slice select
- fix bug in amax
- change log type to debug when ignoring inference failure

2023-12-08 11:17 UTC, zhaochaoxing commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        print("Bernoulli last but one")
可以删掉

2023-12-11 03:00 UTC, zhaochaoxing commented on dicp/dicp/dynamo_bridge/operator.py
> +                        if self.__name__ != "Const"
感觉不一定非要这样

2023-12-13 02:41 UTC, zhaochaoxing approved these changes

2023-12-13 03:39 UTC, KevinfromTJ commented
inference for some ops may have underlying problem:
- SplitD: unknown param and function
- Resahpe: complicated corner cases with other complicated ops needed 
- identity：special case
- memory format

2023-12-15 06:07 UTC, jinminxi104 requested changes

2023-12-15 06:07 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +            dtype=torch.complex64
这个地方，把SplitD名字改一下，改成SplitD4ViewAsComplex，这样就不会造成以后用SplitD的时候出现错误

2023-12-18 15:21 UTC, jinminxi104 requested changes

2023-12-18 15:21 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +            dtype=torch.complex64 if from_view_complex else x_dtype,
这里的from_view_complex为false的情况有经过测试吗？如果没有这样的测例子的话，先assert掉。后续我们仔细研究SplitD之后再加入

2023-12-18 15:21 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +    # TODO: unfinished, need furthur test, PASS
这边是完成了还是未完成？

2023-12-18 15:42 UTC, KevinfromTJ commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +    # TODO: unfinished, need furthur test, PASS
> 这边是完成了还是未完成？

未完成，按照conversion.py这个函数是dynamic shape需要的调用的版本，但是目前的路线是先做完static部分，所以仿照expandD做着

2023-12-20 07:15 UTC, jinminxi104 approved these changes

2023-12-20 07:16 UTC, merged