lyp_clang_tidy: warning uint64_t->int
DeepLink-org/deeplink.framework pull request #518
Opened 2023-12-11 02:42 UTC by lyp-liuyipeng

2023-12-11 06:11 UTC, lljbash requested changes
format

2023-12-11 06:11 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/DIPUDeviceActivity.cpp
> +  constexpr size_t kSecondToMillisecond = 1000;
```suggestion
  constexpr size_t kMillisecondsPerSecond = 1000;
```

2023-12-11 06:11 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/DIPUDeviceActivity.h
> +      const std::set<libkineto::ActivityType>& selectedActivities) override;
我们现在不是没改命名？

2023-12-11 06:11 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/patch.cpp
> +void FlattenToUniformRepresentation(std::vector<std::shared_ptr<Result>>& sorted_results,
放进 unamed ns

2023-12-11 06:11 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/profiler.cpp
> +      constexpr double kSecondToMillisecond = 1e3;
ditto

2023-12-11 06:11 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/profiler/profiler.cpp
> +static constexpr size_t kInitModuleId = 10000;
```suggestion
constexpr size_t kInitModuleId = 10000;
```

2023-12-13 03:52 UTC, lyp-liuyipeng commented on dipu/torch_dipu/csrc_dipu/profiler/DIPUDeviceActivity.h
> +      const std::set<libkineto::ActivityType>& selectedActivities) override;
已改

2023-12-13 03:53 UTC, lyp-liuyipeng commented on dipu/torch_dipu/csrc_dipu/profiler/profiler.cpp
> +static constexpr size_t kInitModuleId = 10000;
已修改

2023-12-13 08:03 UTC, lljbash approved these changes

2023-12-18 03:33 UTC, mrdanielw approved these changes

2023-12-18 03:33 UTC, merged