Op preference mem format
DeepLink-org/deeplink.framework pull request #525
Opened 2023-12-12 07:47 UTC by Wrench-Git

This change will add a TAG in diopi_functions.yaml and the autogen will replace it with the prefered memory format depending on the convert_config.yaml of the device

2023-12-13 10:02 UTC, lljbash requested changes

2023-12-13 10:02 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
> +    auto out0 = at::empty_like(input, input.options(), out0_MemoryFormat);
注意格式，下同

2023-12-13 10:02 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
> +        out0_MemoryFormat = input.suggest_memory_format(),$SUGGESTED_MEMORYFORMAT;
我建议用大括号括起来

取名考虑用 MEMORY_FORMAT_PLACEHOLDER

2023-12-13 10:02 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/op_memory_format_converter.py
来点注释

2023-12-14 07:05 UTC, lljbash approved these changes

2023-12-14 07:05 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/op_memory_format_converter.py
> +import os
这里可以加个 docstring，说一下placeholder 的语法

2023-12-14 07:05 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
> +        (axis==4?(c10::optional<at::MemoryFormat>(${PREFERED_MEMORY_FORMAT_PLACEHOLDER:-c10::nullopt})):(axis==5?(c10::optional<at::MemoryFormat>(${PREFERED_MEMORY_FORMAT_PLACEHOLDER_3D:-c10::nullopt
这里最好能排个版

2023-12-15 08:45 UTC, fandaoyi approved these changes

2023-12-15 09:19 UTC, merged