Ywt/optimize op print info log
DeepLink-org/deeplink.framework pull request #528
Opened 2023-12-13 03:23 UTC by yewentao256

- close print op log info by default
- optimize fetching environment variable

2023-12-13 09:22 UTC, lljbash requested changes
感觉整个事情都没有必要，你是测了最新的分支确定会快吗，我已经把最慢的部分修好了

见 #524 #526

2023-12-13 09:22 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
> +  }();
感觉没有必要

2023-12-13 09:43 UTC, yewentao256 commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
> +  }();
之前改的时候还没有static，目前看起来，如果你已经修了那个问题那确实性能提升不是很大了。不过少一次if应该还是有帮助的，一个iter几万次算子调用，关键路径上1us提升也是一点点

2023-12-13 10:01 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
> +  }();
目前看这些修改只有坏处没有好处，这里少一次 if 在我的知识范畴里没有帮助的，除非能有性能分析支持
@mrdanielw 拍一下吧

2023-12-13 10:06 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
> +  }();
我觉得，回退 cmake，然后这里的输出应该只有读到环境变量的时候才有

2023-12-13 10:10 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
> +  }();
我的意见是， 日志这个还好，文涛这样改也行。  但是 cmake 里改为 false 那个， 因为国春的 这个 DUMP_ARGS 大家用的比较频繁的， 特别是 线上的版本出了问题也要用，现在如果默认不编译，线上复现 问题都会很麻烦， 相比于一点点的性能， 我建议改回 true。

2023-12-13 10:14 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
> +  }();
还有现在 cmake 无法感知脚本参数的变更 （这个之前跟文涛说过），想重新编译个能打印的都很麻烦（需要把已经生成的 autogen 删掉），也不利于日常开发。

2023-12-13 10:20 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
> +  }();
分享一个事， 之前我们线上的一个 文件系统服务，关掉了一个 debug  log， 无法动态打开。然后有一次升级后 写数据出错了， 而且测试/stage 环境均无法复现，没有线上的 debug log 导致 折腾了很久才定位问题。 影响很大。

2023-12-13 11:44 UTC, yewentao256 commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
> +  }();
嗯嗯有道理，已改回默认配置

2023-12-13 11:52 UTC, fandaoyi approved these changes

2023-12-14 06:04 UTC, yewentao256 commented
Close this issue since we have the same one https://github.com/DeepLink-org/deeplink.framework/pull/524

2023-12-14 06:04 UTC, closed without merging