support format cast
DeepLink-org/deeplink.framework pull request #553
Opened 2023-12-20 02:18 UTC by zhaochaoxing

support format cast

2023-12-28 09:32 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/utils/helpfunc.cpp
> +    Py_BEGIN_ALLOW_THREADS ::diopiFormatCast(&context, &out, input,
这个在最新diopi里已经加了，不需要在调用前再加这个。https://github.com/DeepLink-org/DIOPI/pull/762/files

2023-12-28 09:52 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp
> +      .value("ChannelsLast", diopiMemoryFormat_t::ChannelsLast)
这些可以用字符串不导出吗？不同设备有不同的memformat， 到时候在不需要的设备上会不会有很多不需要的代码？能否适当抽象一下？

2023-12-28 12:08 UTC, zhaochaoxing commented on dipu/torch_dipu/csrc_dipu/utils/helpfunc.cpp
> +    Py_BEGIN_ALLOW_THREADS ::diopiFormatCast(&context, &out, input,
好的，去掉了

2023-12-28 12:08 UTC, zhaochaoxing commented on dipu/torch_dipu/csrc_dipu/binding/ExportRT.cpp
> +      .value("ChannelsLast", diopiMemoryFormat_t::ChannelsLast)
好的

2023-12-29 04:59 UTC, lljbash commented
务必等 @Wrench-Git 看过，功能似有重叠之处，或有冲突

2023-12-29 05:41 UTC, lljbash requested changes
似乎没有标记说明这个 tensor 是不是还是 aten strided 兼容的

另外，是不是有些 format 的确是 strided 的，但是不在 c10 的定义里，所以本可以兼容的并没有兼容。

2023-12-29 05:41 UTC, lljbash commented on dipu/tests/python/individual_scripts/test_format_cast.py
这个 test 应该放在 unit 里面，加快测试速度

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStorageImpl.h
> +  static DIPUStorageImpl* GetImplPtr(const at::Tensor& tensor);
保持命名风格一致性

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStorageImpl.h
> +  static DIPUStorageImpl* GetImplPtr(const at::Tensor* tensor);
没有必要做这样的重载，迷惑性很强

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStorageImpl.h
> +class DIPUStorageImpl : public c10::StorageImpl {
增加注释文档

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStorageImpl.h
> +  void set_desc(const diopiStorageDesc_t& desc);
init 和剩下俩的关系不明确，命名具有误导性

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStorageImpl.h
> +  void set_desc(const diopiStorageDesc_t& desc);
```suggestion
  void set_memory_desc(c10::IntArrayRef size,
                 c10::optional<at::MemoryFormat> memory_format_opt);

  void get_diopi_memory_desc(diopiStorageDesc_t* desc) const;

  void set_diopi_memory_desc(const diopiStorageDesc_t& desc);
```

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStorageImpl.h
> +  diopiMemoryFormat_t format_ = diopiMemoryFormat_t::Undefined;
```suggestion
  diopiMemoryFormat_t diopi_memory_format_ = diopiMemoryFormat_t::Undefined;
```

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStorageImpl.cpp
> +void DIPUStorageImpl::release_resources() { StorageImpl::release_resources(); }
没有额外操作，为何要重写

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/EmptyOpsKernel.cpp
> +    if (*memory_format_opt != c10::MemoryFormat::Contiguous) {
减少嵌套

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/EmptyOpsKernel.cpp
> +          c10::StorageImpl::use_byte_size_t(), size_bytes, allocator, true);
```suggestion
          c10::StorageImpl::use_byte_size_t(), size_bytes, allocator, /*resizable=*/true);
```

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/EmptyOpsKernel.cpp
是否测试了对性能的影响？

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/EmptyOpsKernel.cpp
> +          c10::StorageImpl::use_byte_size_t(), size_bytes, allocator, true);
```suggestion
          c10::StorageImpl::use_byte_size_t(), size_bytes, allocator, /*resizable=*/true);
```

2023-12-29 05:41 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUStorageImpl.cpp
> +}
```cpp
swicth (memory_format_opt.value_or(c10::MemoryFormat::Contiguous) {
  ...
```
是不是可读性会好很多

最好把这个对应转换拿出来做一个匿名空间函数 `c10_memory_format_to_diopi_memory_format`，in 一个 c10::MemoryFormat，return 一个 diopiMemoryFormat_t，传入时调 value_or，看起来更清楚简洁

2023-12-29 05:46 UTC, Wrench-Git reviewed
这个改动应该对adaptor的改动是invisible的，为了确保改动不会产生side effect，我觉得可以测试一下改动前后我们跑resnet里，强制memory format cast的次数有没有变化。

2024-01-05 04:51 UTC, closed without merging