Kunlunxin
DeepLink-org/deeplink.framework pull request #556
Opened 2023-12-20 12:53 UTC by brianlcy123

Add kunlunxin backend

2023-12-20 12:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DeepLink-org/deeplink.framework?pullRequest=556) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DeepLink-org/deeplink.framework?pullRequest=556) before we can accept your contribution.<br/><hr/>**brianlcy123** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DeepLink-org/deeplink.framework?pullRequest=556) it.</sub>

2023-12-21 01:05 UTC, caikun-pjlab requested changes
1. deviceimpl.cpp里面不少api都没有实现，例如getDeviceProperties,resetDevice,checkLastError,getDriverVersion,isStreamEmpty等
2. 需要签署一下CLA

2023-12-21 01:05 UTC, caikun-pjlab commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/deviceimpl.cpp
> +void checkLastError() {}
同上

2023-12-21 01:05 UTC, caikun-pjlab commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/vendorapi.h
> +      printf("call a xpu function (%s) failed. return code=%d", #Expr, \
参考 dipu/torch_dipu/csrc_dipu/vendor/cuda/vendorapi.h ，推荐使用 TORCH_CHECK 做出错处理

2023-12-21 07:53 UTC, caikun-pjlab commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/communicatorimpl.cpp
> +#include <pccl.h>
不需要的头文件可以先删除

2023-12-21 07:53 UTC, caikun-pjlab commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/deviceimpl.cpp
> +  std::cout << "cyliu getRuntimeVersion" << std::endl;
删除调试日志

2023-12-21 07:53 UTC, caikun-pjlab commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/deviceimpl.cpp
> +bool isPinnedPtr(const void* p) { return true; }
默认返回false比较好

2023-12-21 11:33 UTC, caikun-pjlab approved these changes

2023-12-21 11:41 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/vendorapi.h
> +#define DIPU_CALLXPU_ERROR(Expr) \
这里写错了吧， 为啥会出现XPU？ 不应该是 klx吗？ 另外那几个文件名也是， XPUGeneratorImpl。 FindXPU。。 不应该在任何地方出现XPU的字样的

2023-12-21 11:44 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/deviceimpl.cpp
> +using xpu_deviceId = int;
vendor 里建议就用vendor 自己的 设备 id， xpu是我们偷用 intel的一个 设备 ，它和DIPU 等价， 和 vendor 设备毫无关系

2023-12-21 11:50 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/vendorapi.h
> +#define DIPU_CALLXPU_ERROR(Expr) \
刚和同事求证了下， KLX 也叫 XPU， 那和我们这边的名字重叠了，看起来很容易混淆。建议至少先把全局变量和 文件名改成 KLX吧

2023-12-22 01:39 UTC, lljbash requested changes

2023-12-22 01:39 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/CMakeLists.txt
> +# option(DIST "whether to use PCCL to implement communicator" OFF)
不要留着无用的注释，若有必要需要文字说明，下同

2023-12-22 01:39 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/deviceimpl.cpp
> +void releaseStream() { return; }
```suggestion
void releaseStream() {}
```

2023-12-22 01:39 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/deviceimpl.cpp
> +      printf("call a xpurt function failed. return code=%d %d", r, nbytes);
能否使用 dipu log

2023-12-22 02:21 UTC, brianlcy123 commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/deviceimpl.cpp
> +void releaseStream() { return; }
已更新

2023-12-22 02:21 UTC, brianlcy123 commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/CMakeLists.txt
> +# option(DIST "whether to use PCCL to implement communicator" OFF)
已更新

2023-12-22 08:52 UTC, brianlcy123 commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/vendorapi.h
> +#define DIPU_CALLXPU_ERROR(Expr) \
已修改

2023-12-22 08:52 UTC, brianlcy123 commented on dipu/torch_dipu/csrc_dipu/vendor/kunlunxin/deviceimpl.cpp
> +      printf("call a xpurt function failed. return code=%d %d", r, nbytes);
已修改

2023-12-22 09:15 UTC, fandaoyi approved these changes

2023-12-22 09:31 UTC, lljbash approved these changes

2023-12-22 09:38 UTC, merged