[DIPU]support using torch profiler on nv
DeepLink-org/deeplink.framework pull request #559
Opened 2023-12-21 07:32 UTC by caikun-pjlab

2023-12-21 07:52 UTC, lljbash requested changes

2023-12-21 07:52 UTC, lljbash commented on dipu/tests/python/unittests/test_profiler_cuda.py
> +        prof.export_chrome_trace("./resnet18_profiler.json")
参照 tests/python/unittests/test_storage.py，扔到一个 tempfile.TemporaryDirectory() 里面去，上面那个测试也是。

2023-12-21 07:52 UTC, lljbash commented on dipu/tests/python/unittests/test_profiler.py
> +os.environ["FORCE_USE_DIPU_PROFILER"] = "True"
可以加到下面的 local_eviron 里面去

2023-12-21 08:10 UTC, yewentao256 approved these changes

2023-12-21 09:16 UTC, lljbash commented on dipu/tests/python/unittests/test_profiler.py
> +os.environ["FORCE_USE_DIPU_PROFILER"] = "True"
更正：要放到 individual test 里去

2023-12-21 09:52 UTC, caikun-pjlab commented on dipu/tests/python/unittests/test_profiler_cuda.py
> +        prof.export_chrome_trace("./resnet18_profiler.json")
已修改

2023-12-21 09:53 UTC, caikun-pjlab commented on dipu/tests/python/unittests/test_profiler.py
> +os.environ["FORCE_USE_DIPU_PROFILER"] = "True"
这个测例放到dipu/tests/python/individual_scripts/test_dipu_profiler.py里面去了

2023-12-22 02:08 UTC, lljbash approved these changes

2023-12-22 02:14 UTC, merged