[dicp][ascend] infer op resinfo and run single op 231222
DeepLink-org/deeplink.framework pull request #562
Opened 2023-12-22 09:52 UTC by KevinfromTJ

- finish more ops' inference and running
- update corresponding tests

2023-12-24 15:36 UTC, jinminxi104 requested changes

2023-12-24 15:36 UTC, jinminxi104 commented on dicp/test/ascend_scripts/ops/run_test_ops.sh
> +TEST_DICP_INFER=1
TEST_DICP_INFER在这个脚本里没有被用到，为什么放在这里？后续有什么计划用吗？

2023-12-24 15:36 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if not isinstance(b, torch.fx.proxy.Proxy):
1. 这段ne的代码和后面的lt一样，把这些二元比较的代码写成一个函数。
2. 这段代码的意思是说，如果a是f16，先要构建一个f32的const，再cast成f16?华为不支持构建f16，却支持cast成f16？

2023-12-24 15:36 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +    # TODO: unfinished, need furthur test, PASS
这个PASS是上一个pr我觉得奇怪删掉了。这里是有什么特殊含义吗？

2023-12-24 15:36 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/infer_res_utils.py
>      similar to get_op_const_arg_kwarg()
这句comment是什么意思？我没找到get_op_const_arg_kwarg()

2023-12-25 07:01 UTC, KevinfromTJ commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +    # TODO: unfinished, need furthur test, PASS
rebase时手误了

2023-12-25 07:07 UTC, KevinfromTJ commented on dicp/test/ascend_scripts/ops/run_test_ops.sh
> +TEST_DICP_INFER=1
> TEST_DICP_INFER在这个脚本里没有被用到，为什么放在这里？后续有什么计划用吗？

这是测试infer_shape_dtype用的，在dicp/dynamo_bridge/graph.py定义，因为llama推理测试时不带infer_shape_dtype，所以单独在单测（run_test_ops.sh）中设置

2023-12-25 07:10 UTC, KevinfromTJ commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if not isinstance(b, torch.fx.proxy.Proxy):
> 2. 这段代码的意思是说，如果a是f16，先要构建一个f32的const，再cast成f16?华为不支持构建f16，却支持cast成f16？
好像是的，这段代码不是我写的，仿照其他人已经实现好的二元比较算子来修bug

2023-12-25 07:54 UTC, KevinfromTJ commented
暂时忽略ge和gt，看起来有点不一样，没有转16位

2023-12-25 15:07 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if not isinstance(b, torch.fx.proxy.Proxy):
@zhaochaoxing @tangzhiyi11 看下这里的逻辑？

2023-12-25 15:25 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/infer_res_utils.py
>      similar to get_op_const_arg_kwarg()
“similar to get_op_const_arg_kwarg()”
我指这句。

2023-12-25 15:34 UTC, KevinfromTJ commented
之前版本改后漏删了的注释，没用的


&nbsp;


kevin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月25日(星期一) 晚上11:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DeepLink-org/deeplink.framework] [dicp][ascend] infer op resinfo and run single op 231222 (PR #562)





 
@jinminxi104 commented on this pull request.
 
 
In dicp/dicp/vendor/AscendGraph/infer_res_utils.py:
 &gt; -    (including value and shape) instead of constructing a fakeTensor, which will neglect a tensor's value. -    input: -        - const_arg: Tuple (new_args,kwargs) -            - new_args: Tuple, identical to input-"new_args" of operator Const -            - kwargs: dict, identical to input-"kwargs" of operator Const - -    output: -        - arg0: list, value of "Const"'s input -        - arg2: list, shape of "Const"'s input -    """ -    new_args = const_arg[0] -    arg0 = new_args[0] -    arg2 = new_args[2] -    return arg0, arg2 - -  def get_op_const_arg_kwarg(const_arg):      """      similar to get_op_const_arg_kwarg()  
“similar to get_op_const_arg_kwarg()”
 我指这句。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-12-25 15:38 UTC, jinminxi104 commented on dicp/test/ascend_scripts/ops/run_test_ops.sh
> +TEST_DICP_INFER=1
应该是export TEST_DICP_INFER=1

2023-12-27 07:38 UTC, zhaochaoxing commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if not isinstance(b, torch.fx.proxy.Proxy):
> @zhaochaoxing @tangzhiyi11 看下这里的逻辑？

@jinminxi104 构造tensor时需要传入变量的地址和length，c++里面只能构造一个float类型变量，然后取地址传入，length只能等于4个字节，这就造成了无法通过C++构造float16类型的tensor。

2023-12-28 09:20 UTC, zhaochaoxing approved these changes

2023-12-28 11:40 UTC, jinminxi104 approved these changes

2023-12-28 11:44 UTC, merged