Support stable-diffusion in tops
DeepLink-org/deeplink.framework pull request #568
Opened 2023-12-26 03:28 UTC by yao-fengchen

2024-01-06 16:52 UTC, jinminxi104 requested changes

2024-01-06 16:52 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/config.py
> +                   aten.bmm.default, aten.copy.default, aten.stack.default]
stack为什么删掉？

2024-01-06 16:52 UTC, jinminxi104 commented on dicp/test/op/test_unsqueeze.py
> +    @pytest.mark.parametrize("sizes", [Size(5, (2, 4)), Size((5,), (5, 3)),
这里是一个Size里面两个shape，这里为什么是（5, (2, 4))？

2024-01-06 16:52 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +        dim = dim % len(a.node.args) if "ret_tuples" in a.node.name else dim % len(a.node.meta["val"])
这个ret_tuples被弃用了吧？可以连同定义一起删了

2024-01-06 16:52 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +        offset = len(out_shape) - len(grad_output_shape)
我觉得这几个变量命名和我理解的不太一样，我们offline讨论一下

2024-01-06 16:52 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +        offset = len(out_shape) - len(in_shape)
我觉得这几个变量命名和我理解的不太一样，我们offline讨论一下

2024-01-06 16:52 UTC, jinminxi104 commented on dicp/dicp/dynamo_bridge/op_transformer.py
> +                self.infer_shape_dtype(module)
这里为什么要加这个infer？为了aten2tops的1对多的case（varmean）？这个infer的代码是哪里来的？

2024-01-06 16:52 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/codegen/enflame.py
> +            self.build_graph_code.writeline(
这段代码修改的case 是什么？添加comment说明

2024-01-08 06:14 UTC, yao-fengchen commented on dicp/dicp/vendor/TopsGraph/config.py
> +                   aten.bmm.default, aten.copy.default, aten.stack.default]
燧原hlir_builder有Stack

2024-01-08 06:15 UTC, yao-fengchen commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +        dim = dim % len(a.node.args) if "ret_tuples" in a.node.name else dim % len(a.node.meta["val"])
当时是为了解决var_mean，现在可以删掉

2024-01-08 06:16 UTC, yao-fengchen commented on dicp/test/op/test_unsqueeze.py
> +    @pytest.mark.parametrize("sizes", [Size(5, (2, 4)), Size((5,), (5, 3)),
这里是为了测试一个Scalar的Unsqueeze

2024-01-08 06:17 UTC, yao-fengchen commented on dicp/dicp/vendor/TopsGraph/codegen/enflame.py
> +            self.build_graph_code.writeline(
这里是为了解决Scalar情况下Unsqueeze时形状不对的问题

2024-01-08 07:15 UTC, yao-fengchen commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +        offset = len(out_shape) - len(grad_output_shape)
offset-->rank_diff

2024-01-08 07:15 UTC, yao-fengchen commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +        offset = len(out_shape) - len(in_shape)
offset-->rank_diff

2024-01-12 05:49 UTC, yao-fengchen commented on dicp/dicp/dynamo_bridge/op_transformer.py
> +                self.infer_shape_dtype(module)
已在新的commit移除tops的aten pattern，所以这部分现在也不需要了

2024-01-12 06:59 UTC, CyCle1024 approved these changes

2024-01-12 10:00 UTC, jinminxi104 approved these changes

2024-01-14 14:07 UTC, merged