[DICP]Add llama_finetune test.
DeepLink-org/deeplink.framework pull request #571
Opened 2023-12-26 10:50 UTC by Reinerzhou

1. Fix softmax match.
2. Set mock_cuda true.
3. Add llama_finetune test.

2024-01-06 17:02 UTC, jinminxi104 approved these changes

2024-01-08 06:18 UTC, CyCle1024 requested changes

2024-01-08 06:18 UTC, CyCle1024 commented on dicp/dicp/vendor/TopsGraph/tops_op.py
> +        self.torch_op = aten.softmax
为什么要改这个？

2024-01-08 06:18 UTC, CyCle1024 commented on dicp/scripts/ci/tops/ci_tops_build_env.sh
> +export DIPU_MOCK_CUDA=True
DIPU_MOCK_CUDA是运行时环境变量，不是构建时环境变量

2024-01-08 06:18 UTC, CyCle1024 commented on dicp/test/common/prompter.py
> +models_dir = os.environ.get("LLAMA_FINETUNE_DIR", "/home/cse/projects/pujiang/llama_finetune")
这里的环境变量虽然有默认值，应该在ci测试脚本的环境变量中体现出来，以后更改目录应该也在ci脚本中实现。

2024-01-08 07:08 UTC, wugeshui commented
需要先解决冲突才能跑ci

2024-01-08 07:25 UTC, Reinerzhou commented on dicp/dicp/vendor/TopsGraph/tops_op.py
> +        self.torch_op = aten.softmax
已添加注释。

2024-01-08 07:25 UTC, Reinerzhou commented on dicp/scripts/ci/tops/ci_tops_build_env.sh
> +export DIPU_MOCK_CUDA=True
已更改。

2024-01-08 07:25 UTC, Reinerzhou commented on dicp/test/common/prompter.py
> +models_dir = os.environ.get("LLAMA_FINETUNE_DIR", "/home/cse/projects/pujiang/llama_finetune")
已更改。

2024-01-08 15:19 UTC, CyCle1024 approved these changes

2024-01-09 03:12 UTC, merged