[DIPU] disable custom fallback ops partly.
DeepLink-org/deeplink.framework pull request #592
Opened 2024-01-04 03:09 UTC by Reinerzhou

**Motivation and Context  背景**

-   由于dipu存在自定义的dispatch逻辑(包括custom_fallback)，影响了dynamo中对meta key的dispatch行为，在linear设为custom_fallback后，会影响linear_backward的dispatch行为。

**Description  描述  功能抽象**

-   通过增设一个环境变量DIPU_DISABLE_CUSTOM_FALLBACK以及disable_custom_fallback_ops_list在必要时禁用custom_fallback的逻辑（默认开启custom_fallback）。

**类别 （Bug 修复|new feature| Intenal SW ）**

- Bug 修复

2024-01-04 07:54 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +    }                                                                         \
1. 这部分逻辑建议挪到88行上面，使影响范围减小。这部分代码会影响启动速度，只在必要的运行分支上运行。
2.  custom_fallback 是配置文件中配置的，在以后的版本中，linear 可能不是custom_fallback，而是其他的什么算子custom_fallback 了
3. custom_fallback 只在真正发生fallback的情况下才会起作用，如果走到了fallback ,是不是该算子没有适配？
4. 如果算子必须fallback,那是否所有fallback了的算子都必须disable fallback? 这个 disable_custom_fallback_ops_list是不是不需要？

2024-01-04 09:07 UTC, Reinerzhou commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +    }                                                                         \
1.这个会修改重新推下代码，同时考虑把list的初始化和判断也放到env_value >= 1的分支内部，是不是也更好些；
2.确实有这个问题，目前配置文件中几个custom_fallback为True的只有linear导致了编译这边的错误，以后如果取消了linear或者新增其他会导致编译模式下错误的算子，会需要反复修改这里的代码，现在思路是单独设置一个环境变量如：DIPU_DISABLE_CUSTOM_FALLBACK_OPS="+linear,+.."，而不是现在这种不鲁棒的方式来控制是不是更好；
3.不是，主要还是linear配置为true之后dicp的编译流程会因为dipu中注册在xpu这个DispatchKey上的impl函数逻辑变化而break掉；现在的修改方式是希望linear算子跟没有fallback时候一致，即47行那个入口；同时在没有设置特定环境变量的情况下维持dipu原本的注册逻辑；
4.不是，所有fallback了的算子中有的在编译下需要disable如linear，有的不能disable如copy_，原因如3；当然，如果按照2修改的话就不需要纠结这个问题了。

2024-01-08 08:56 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +          (std::string(env).find(std::string(opname) + ",") <                 \
export DIPU_DISABLE_CUSTOM_FALLBACK_OPS=linear
export DIPU_DISABLE_CUSTOM_FALLBACK_OPS=linear,
这俩结果不一样吧

2024-01-08 09:28 UTC, zhaoguochun1995 approved these changes

2024-01-08 10:56 UTC, Reinerzhou commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +          (std::string(env).find(std::string(opname) + ",") <                 \
已修复。

2024-01-09 11:09 UTC, lljbash requested changes
和现有变量有冲突，优先级如何
需要加上对应的测例
@fandaoyi : 是否有其他方式解决

2024-01-11 06:45 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +    }                                                                         \
‘由于dipu存在自定义的dispatch逻辑(包括custom_fallback)，影响了dynamo中对meta key的dispatch行为’。 没理解，dipu 注册的是 xpu key， 是如何影响到meta key 的分派行为的？

2024-01-11 06:54 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +    }                                                                         \
是否是因为 fallback linear 影响了默认的 linear composite op的分派过程，和meta device的 不一致了。

2024-01-11 08:20 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +    }                                                                         \
如果是上述问题， 建议这个宏的名字改下， 叫做 keep_composite_op_dispatch  或者 keep_composite_op_priority 啥的。总之 这个flag要做啥，就明确的写啥。 这种在 fallback 上面又加一个 diasble fallback 的做法我感觉颇为奇怪。  后面可以在 autogen 里加个 flag， 显示表明某个 算子是 composie，可以有特殊的fallback 注册逻辑。

2024-01-11 08:21 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +      }                                                                       \
@lljbash  我的评论加到国春的下面了

2024-01-11 08:26 UTC, Reinerzhou commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +    }                                                                         \
在注册xpu key后影响到了linear_backward的dispatch，在 #593 中有其详细报错和dipatch的具体行为。

2024-01-12 06:44 UTC, Reinerzhou commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +      }                                                                       \
1.目前优先级高于算子注册，用于编译这边让特定算子保持默认的torch impl；
2.已添加测例，保证dipu这边原有的逻辑不受影响；
3.逻辑已经独立到oputils中。

2024-01-12 06:44 UTC, Reinerzhou commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +    }                                                                         \
1.目前优先级高于算子注册，用于编译这边让特定算子保持默认的torch impl；
2.已添加测例，保证dipu这边原有的逻辑不受影响；
3.逻辑已经独立到oputils中。

2024-01-12 07:30 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.hpp
> +// for non-custom ops through function dipuKeepTorchopDefaultImpl firstly in the
把这段单独拉出来吧 /**/ 或者空行。 另外说明下， 我们现在借用 force fallback 来处理  keepdefault 的行为。

2024-01-12 07:34 UTC, fandaoyi approved these changes

2024-01-12 09:22 UTC, lljbash approved these changes
细节建议改一下

2024-01-12 09:22 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
> +  const char* env = std::getenv("DIPU_KEEP_TORCHOP_DEFAULT_IMPL_OPS");
```suggestion
  static const char* env = std::getenv("DIPU_KEEP_TORCHOP_DEFAULT_IMPL_OPS");
```

2024-01-17 09:02 UTC, merged