[dipu]Zcx/memory format cast
DeepLink-org/deeplink.framework pull request #602
Opened 2024-01-05 05:02 UTC by zhaochaoxing

add custom api memory_format

2024-01-05 05:09 UTC, zhaoguochun1995 approved these changes

2024-01-05 07:41 UTC, lljbash requested changes

2024-01-05 07:41 UTC, lljbash commented on dipu/tests/python/unittests/test_format_cast.py
> +        dipu_format_list2 = [30, 33, 30, 2, 33, 2, 30, 32, 2, 32, 2]
这个有点恐怖了，还是得把 enum 导出来吧

2024-01-05 07:45 UTC, zhaochaoxing commented on dipu/tests/python/unittests/test_format_cast.py
> +        dipu_format_list2 = [30, 33, 30, 2, 33, 2, 30, 32, 2, 32, 2]
上午review刚讨论完定的删掉enum，用int

2024-01-05 08:21 UTC, fandaoyi commented on dipu/tests/python/unittests/test_format_cast.py
> +        dipu_format_list2 = [30, 33, 30, 2, 33, 2, 30, 32, 2, 32, 2]
刚才我又和国春对了下。基本的结论如下。1. dipu 侧需要一个统一的 memformat的定义。否则没法使用了。2. 这个定义是否要放到 diopi rt 里 以及 diopiCustomFormatCast 这几个 op 是否需要感知这个 memformat。 这个是和国春的分歧。

2024-01-05 08:26 UTC, fandaoyi commented on dipu/tests/python/unittests/test_format_cast.py
> +        dipu_format_list2 = [30, 33, 30, 2, 33, 2, 30, 32, 2, 32, 2]
如果 认为 统一的memformat 不需要放到 diopi-rt 里， 那就 dipu里自行定义一个 （就是把原来那个 diopi rt 里面的 拿出来）， 并对不同 vendor 做转换。
如果认为统一的memformat 需要放到 diopi-rt 里，就恢复原来的 diopi_memformat 定义。
目前看， 华为的那几个 memformat 都不算啥特有的格式，都是通用格式的某种变化 （分形 or 循环顺序变换，分块啥的）， 其他厂商也可以定义这样的格式。 如果将来真的有非常特化的 memformat， 可以在通用 memformat 枚举里 定义里增加新的 特化项，但是暂时没有必要 （根据个人对存储格式的理解， 我认为永远都不会特化，没有哪个厂商能真正提出啥新的 存储格式， 无非改个名字，加点自定义的分割啥的，完全可以用通用格式来指代）。

2024-01-05 08:32 UTC, fandaoyi commented on dipu/tests/python/unittests/test_format_cast.py
> +        dipu_format_list2 = [30, 33, 30, 2, 33, 2, 30, 32, 2, 32, 2]
进一步，后续 dipu memformat 是否可以对这些格式做些整合，方便些通用处理？ 但是至少 先定义出来。

2024-01-05 08:52 UTC, fandaoyi commented on dipu/torch_dipu/dipu/__init__.py
> +    "format_cast"
如果是 custom？ 是否单独放到 一个 custom.py 下？

2024-01-05 08:52 UTC, fandaoyi commented on dipu/torch_dipu/__init__.py
> +    torch.Tensor.diopi_format = property(_C.diopi_format)
这个别和上面那两个类比， 那些也不是 pybind 这一套的。 相关的接口 建议放一起导出。  然后 dipu.__Init__.py __all__ 统一导出到外层。外面直接使用 diopi_format。参考其他的

2024-01-05 08:59 UTC, zhaoguochun1995 commented on dipu/tests/python/unittests/test_format_cast.py
> +        dipu_format_list2 = [30, 33, 30, 2, 33, 2, 30, 32, 2, 32, 2]
硬件差异客观存在，华为上用的那些memformat，在之前的设备如，寒武纪、华为、cuda等其他设备上都不会用到。放到diopirt.h这个公共头文件里对其他设备来说是个干扰

2024-01-05 09:00 UTC, zhaoguochun1995 commented on dipu/tests/python/unittests/test_format_cast.py
> +        dipu_format_list2 = [30, 33, 30, 2, 33, 2, 30, 32, 2, 32, 2]
有必要抽象一下

2024-01-05 09:44 UTC, zhaochaoxing commented on dipu/torch_dipu/dipu/__init__.py
> +    "format_cast"
放到单独的custom.py里了

2024-01-05 09:44 UTC, zhaochaoxing commented on dipu/torch_dipu/__init__.py
> +    torch.Tensor.diopi_format = property(_C.diopi_format)
好的，改成torch_dipu.get_format(tensor)的函数形式了

2024-01-08 04:26 UTC, lljbash requested changes

2024-01-08 04:26 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/utils/helpfunc.hpp
> +CustomFormat_t get_format(const at::Tensor& tensor);
叫做 native format 比较好，这个和传统的 format 又不是一个层级的东西了

2024-01-08 04:26 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/utils/helpfunc.hpp
> +enum class CustomFormat_t {
这里放一个前向声明，NPU vendor 里给定义，下面函数声明改成弱符号，实现使用条件编译，就简洁地完成了目标，且暴露了最少的信息，后续也很容易修改

2024-01-09 08:17 UTC, lljbash approved these changes

2024-01-11 11:56 UTC, fandaoyi commented on dipu/CMakeLists.txt
> +add_compile_definitions(${DIPU_VENDOR_NAME_FLAG_DEF}=1)
另一个问题， DIPU_VENDOR_NAME_FLAG_DEF 似乎没有被使用， 唯一一个把 vendor 作为flag判断的地方 是 deviceapis.cpp 里， 还是 用的是 DIPU_VENDOR_NAME。所以 FLag_Def 是否还需要？

2024-01-11 11:56 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/device/basedef.h
> +#define DIPU_STRINGIFY_AFTER_EXPANSION(x) DIPU_STRING(x)
这个和直接用 DIPU_STRING有啥区别啊？

2024-01-11 11:56 UTC, fandaoyi commented on dipu/CMakeLists.txt
> +add_compile_definitions(DIPU_VENDOR_NAME=${UsedVendor})
备注下：  dipu 最好还是用 vendor 目录和接口注册来隔离 不同vendor 的差异。这种基于vendor的宏要尽可能控制使用范围。否则 torch_version 和 vendor 两个维度的差异都通过编译宏来处理的话，代码逻辑会不可收拾。
暂定为： 某些面向 python， 透传到 diopi 的 数据类型定义可以用。dipu 自身的业务逻辑尽量 避免使用。
后面我打算把这个原则说明 加到 新增的 config.h with all macros 文件里。

2024-01-11 12:05 UTC, fandaoyi approved these changes

2024-01-15 06:26 UTC, merged