[DICP] Implement paras auto cast in some binary ops.
DeepLink-org/deeplink.framework pull request #615
Opened 2024-01-09 10:38 UTC by Reinerzhou

Implement paras auto cast in some binary ops.

2024-01-21 16:33 UTC, jinminxi104 approved these changes

2024-01-24 03:41 UTC, CyCle1024 requested changes

2024-01-24 03:41 UTC, CyCle1024 commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +        if isinstance(a, Proxy) and isinstance(b, Proxy):
建议整块重复逻辑也封装为一个函数，binary dtype cast

2024-01-24 04:21 UTC, jinminxi104 requested changes

2024-01-24 04:21 UTC, jinminxi104 commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +def get_cast_dtype(
这块也和华为的整合一下，找个common的地方放一下

2024-01-24 11:05 UTC, Reinerzhou commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +        if isinstance(a, Proxy) and isinstance(b, Proxy):
done.

2024-01-24 11:06 UTC, Reinerzhou commented on dicp/dicp/vendor/TopsGraph/conversion.py
> +def get_cast_dtype(
done.

2024-01-24 11:48 UTC, CyCle1024 approved these changes

2024-01-29 06:30 UTC, jinminxi104 approved these changes

2024-01-29 06:30 UTC, merged