Support ascend stable_diffusion.
DeepLink-org/deeplink.framework pull request #623
Opened 2024-01-12 07:41 UTC by pdx1989

Support ascend stable_diffusion, precision aligned.

2024-01-18 15:14 UTC, jinminxi104 requested changes

2024-01-18 16:26 UTC, jinminxi104 requested changes

2024-01-18 16:26 UTC, jinminxi104 commented on dicp/test/model/test_stable_diffusion.py
> +        # pytorch monkey patch for ascendgraph backend
这段是为什么？为什么遂愿不需要？

2024-01-19 01:00 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        num_split = int(shape[dim] / split_size)
这种情况多出来的余数会加到最后一份子集中，看上去应该是取下整

2024-01-19 01:01 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +                return gather
ok

2024-01-19 01:13 UTC, pdx1989 commented on .github/workflows/_runs-on-ascend.yml
> +              cd /mnt/cache/share/deeplinkci/dicp_env/diffusers && \
没有修改，那我diffusers改为ci机器上长期安装的方式

2024-01-19 01:31 UTC, pdx1989 commented on dicp/test/model/test_stable_diffusion.py
> +        # pytorch monkey patch for ascendgraph backend
燧原那边已将类似的monkey patch加到了compile_fx和utils里面、普遍性地引入，单元测试这边应该不需要了

2024-01-19 06:19 UTC, pdx1989 commented on dicp/test/model/test_stable_diffusion.py
> +        # pytorch monkey patch for ascendgraph backend
燧原那边为compile_fx、utils统一添加了pt_patch，相当于这边的monkey patch，单元测试这边现在不需要了

2024-01-19 07:46 UTC, zhaochaoxing approved these changes

2024-01-21 16:26 UTC, jinminxi104 approved these changes

2024-01-22 06:12 UTC, merged