[dicp]Cjt/support resnet50 train
DeepLink-org/deeplink.framework pull request #635
Opened 2024-01-15 12:05 UTC by KevinfromTJ

support training resnet50 in ascend

2024-01-17 08:29 UTC, KevinfromTJ commented
TODO：需要往华为ci里加resnet50环境

2024-01-22 13:36 UTC, zhaochaoxing approved these changes

2024-01-22 16:10 UTC, jinminxi104 requested changes

2024-01-22 16:10 UTC, jinminxi104 commented on dicp/test/model/test_resnet50.py
> +            assert torch.allclose(cpu_real_loss.repeat(1).detach(), dicp_real_loss.repeat(1).cpu().detach(), atol=1e-01, equal_nan=True)
repeat(1)为了什么？

2024-01-22 16:10 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        edges = {bn_update.node.name + "_edge_name": [
添加“edge_name”的目的是什么？

2024-01-22 16:19 UTC, KevinfromTJ commented
1.华为这边dicp和ascend输出好像一个标量一个是1维张量，torch allclose报错shape '[1]'和'[]'无法广播？这个当时没找到是不是其他地方的问题，repeat(1)把标量变成1维张量
不知道遂原那边输出的loss是什么样的，有没有这种问题
2.这个得问赵老师，个人理解是batchnorm中有一些参数和要保存的量，像IdentityN这种算子会连到后续五个变量的Identity算子形成一个图或者树的结构，可能是华为接口要求也可能是自己定义的，当时出错的原因就是和codegen的ascend.py里面的函数没统一命名，我只是把它们都改过来
&nbsp;


kevin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月23日(星期二) 凌晨0:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DeepLink-org/deeplink.framework] [dicp]Cjt/support resnet50 train (PR #635)





 
@jinminxi104 requested changes on this pull request.
 
 
In dicp/test/model/test_resnet50.py:
 &gt;              dicp_optimizer.zero_grad()              dicp_real_loss.backward()              dicp_optimizer.step()   -            assert torch.allclose(cpu_real_loss.detach(), dicp_real_loss.cpu().detach(), atol=1e-01, equal_nan=True) +            # assert torch.allclose(cpu_real_loss.detach(), dicp_real_loss.cpu().detach(), atol=1e-01, equal_nan=True) +            assert torch.allclose(cpu_real_loss.repeat(1).detach(), dicp_real_loss.repeat(1).cpu().detach(), atol=1e-01, equal_nan=True)  
repeat(1)为了什么？
 
 
In dicp/dicp/vendor/AscendGraph/conversion.py:
 &gt; @@ -794,7 +794,7 @@ def _native_batch_norm_legit_functional(self, x, weight, bias, running_mean, run                                      bn_reduce, 1, weight, bias,                                      running_mean, running_var, eps, momentum))          # 3. tie all results: result, saved_mean, saved_invstd -        edges = {bn_update.node.name: [ +        edges = {bn_update.node.name + "_edge_name": [  
添加“edge_name”的目的是什么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-01-24 06:24 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        edges = {bn_update.node.name + "_edge_name": [
talked offline

2024-01-24 06:24 UTC, jinminxi104 approved these changes

2024-01-24 06:25 UTC, merged