[dicp]zcx/support float16 for ascend
DeepLink-org/deeplink.framework pull request #662
Opened 2024-01-23 06:09 UTC by zhaochaoxing

支持float16，消除cast算子

2024-01-23 08:41 UTC, tangzhiyi11 commented on dicp/dicp/third_party/half/ChangeLog.txt
> +Release Notes											{#changelog}
放 third_party 下面的话，就按照 submodule 方式拉取吧

2024-01-23 09:15 UTC, zhaochaoxing commented on dicp/dicp/third_party/half/ChangeLog.txt
> +Release Notes											{#changelog}
这个half比较简单，而且还不在github上。

2024-01-23 09:21 UTC, tangzhiyi11 approved these changes

2024-01-24 03:51 UTC, jinminxi104 requested changes
确认一下，在`pip install .`的方式下，这个half的库会被复制到conda下吗？
我记得是不是要在setup.py里面加点东西？

2024-01-24 09:53 UTC, zhaochaoxing commented
> 确认一下，在`pip install .`的方式下，这个half的库会被复制到conda下吗？ 我记得是不是要在setup.py里面加点东西？

多谢提醒，已改正。

2024-01-24 09:56 UTC, jinminxi104 approved these changes

2024-01-24 09:57 UTC, merged