[DIPU] Use mixed scalar type instead of f32 in group_norm.
DeepLink-org/deeplink.framework pull request #663
Opened 2024-01-23 07:21 UTC by wiryls

尝试修复一个问题。当前 GroupNorm 使用了固定的 float32 类型作为均值、方差等返回值，这里复用了 torch 的判断逻辑处理 fp16 及混合精度的类型。

参考：[`mixed_data_type.h`](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cpu/mixed_data_type.h)

2024-01-23 09:29 UTC, fandaoyi approved these changes

2024-01-23 09:30 UTC, lljbash requested changes

2024-01-23 09:30 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/aten/ops/OpUtils.hpp
> +auto unwrap_or(T&& x, U&& fallback) -> decltype(x.has_value(), x.value()) {
U 不用先构造吧，失败了再构造

就叫 unwrap_or_emplace 吧

2024-01-24 07:54 UTC, lljbash approved these changes

2024-01-26 07:57 UTC, merged