[dicp][ascend] Optimize stable_diffusion performance.
DeepLink-org/deeplink.framework pull request #704
Opened 2024-02-28 09:00 UTC by pdx1989

Optimize stable_diffusion performance, with the result dicp 8s compared to torch_npu 11s.

2024-02-29 08:24 UTC, jinminxi104 requested changes

2024-02-29 08:24 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +        if keep_dtype == 1:
这个地方直接op.set_attr_int("_keep_dtype", keep_dtype)可以吗

2024-02-29 08:24 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/opset_convert.py
> +def ascendgraph_infer_shape(
infershape 分开两个芯片的目的是什么？

2024-02-29 08:24 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/opset_convert.py
> +    AtenToAscendTransformer(gm).get_singleton(gm)
为什么有这一句？

2024-02-29 08:24 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +    fp32_bmm = int(sd_flag) ^ 1
直接fp32_bmm = os.environ.get("bmm_fp16"， 1)这样行吗？ 更加可读一点

2024-02-29 08:42 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/opset_convert.py
> +def ascendgraph_infer_shape(
因为华为的pattern替换需要在infer_shape的函数中执行，与燧原那边的流程有所区别

2024-02-29 08:49 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +    fp32_bmm = int(sd_flag) ^ 1
已用类似的表达替换，并添加注释

2024-02-29 08:59 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +        if keep_dtype == 1:
已经修改

2024-02-29 09:00 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/opset_convert.py
> +    AtenToAscendTransformer(gm).get_singleton(gm)
调试性代码未删干净

2024-03-01 07:11 UTC, jinminxi104 approved these changes

2024-03-01 07:36 UTC, yao-fengchen approved these changes

2024-03-01 07:47 UTC, zhaochaoxing approved these changes

2024-03-01 12:48 UTC, merged