Zgc/dipu improve memory usage efficiency
DeepLink-org/deeplink.framework pull request #729
Opened 2024-03-14 03:37 UTC by zhaoguochun1995

2024-03-14 03:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DeepLink-org/deeplink.framework?pullRequest=729) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DeepLink-org/deeplink.framework?pullRequest=729) before we can accept your contribution.<br/><hr/>**zhaoguochun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DeepLink-org/deeplink.framework?pullRequest=729) it.</sub>

2024-03-14 04:54 UTC, lljbash requested changes

2024-03-14 04:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +    while (!async_mem_pool()->empty()) {
这里有什么区别

2024-03-14 04:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +    if (async_mem_pool()->size() > 10) {
magic number

2024-03-14 04:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBSCachingAllocator.cpp
> +    if (idel_blocks.empty() || async_mem_pool()->size() > 10) {
ditto

2024-03-14 04:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUAsyncResourcePool.h
>    virtual size_t size() = 0;
size 为什么不是 const，其他几个接口类似

2024-03-14 04:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual ~MemoryAlignmentStrategy() = default;
同上个 pr

2024-03-14 05:13 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +    if (async_mem_pool()->size() > 10) {
对这个的作用存疑。 前面 restore() 已经有对 async_mem_pool 的check 和 显存回收的逻辑， 足够用来回收显存了。 这里加了 非空 就等待 并 ‘让出’当前线程的逻辑，  整体来看只会把原来的 显存分配失败后等待的开销，‘更大的平摊' 到线程运行过程中了。 并不会提升速度。

2024-03-14 05:13 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +    if (async_mem_pool()->size() > 10) {
如果仅仅是为了控速 +控制显存最大分配量，先把这个设置成一个方便修改的变量。

2024-03-14 06:46 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +    while (!async_mem_pool()->empty()) {
！empty 效率比size()>0 高

2024-03-14 06:46 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +    if (async_mem_pool()->size() > 10) {
没有说提升速度，主要是减少显存占用。修改后internlm_7b num_layer=32能跑起来，修改之前是跑不起来的。

2024-03-14 06:46 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.cpp
> +namespace {
这个pr依赖前面的pr,前面的还没合

2024-03-14 06:48 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
静态多态意味着将华为的要东西放到公共核心的头文件里，编译时要能找的到。

2024-03-14 06:49 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
不同设备的策略不想耦合在一起，也没有彼此依赖的关系

2024-03-14 07:20 UTC, yewentao256 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +    while (!async_mem_pool()->empty()) {
这里追求性能的话，或许用std::shared_mutex读可共享或许更好？

2024-03-14 08:22 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +    while (!async_mem_pool()->empty()) {
读写分开分级确实更好，不过会引入c++17的依赖

2024-03-14 08:33 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
这块没看明白，xx.cc里做的，怎么影响到bb.cc呢。我是想通过在xxa.cc或xxb.cc里做配置，在另外的一个bb.cc里用。bb.cc而且可能是一个提前编译好的动态库。

2024-03-14 09:43 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +    while (!async_mem_pool()->empty()) {
老版本不管了？

2024-03-14 11:03 UTC, caikun-pjlab approved these changes

2024-03-15 01:17 UTC, yewentao256 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUBFCachingAllocator.cpp
> +    while (!async_mem_pool()->empty()) {
DIOPI已经升到C++17了，dipu感觉也可以升

2024-03-15 03:06 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
个人意见： 吴仪这个我感觉 和现在 deviceapis.h 里的接口函数定义差不多。 国春这个接口没有运行时修改的需求， 但是会有 初始化时配置的需求。   关于混用策略的问题，之前 allocator 实例放到 函数的静态局部成员里时就出现过这个问题。 现在是一个全局变量，初始化时间应该是有保证的。

2024-03-15 03:21 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
一个简单的东西没必要搞哪些花里胡哨的东西。现在的case是一般不需要做什么配置，用默认的就可以，但是有些情况下，可能又有一些特殊的要求。在适配新设备的时候，一般设备不需为allocator 做任何额外的东西,他们根本不需要感知这些。

2024-03-15 03:25 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
内存对齐策略一般不需要运行时修改。但有些情况下可能有需要？或者以后有什么设备是需要的？我现在这种做法也是可以做到运行时修改的。

2024-03-15 03:27 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
关于初始化顺序还有个问题， 我们的 统一 init 始终没有而且看起来也不会有了。。。后面先把 每个 vendor 所有的库加载时初始化放到一个初始化变量里，这样也好查。。然后 导入时初始化 都走 initializeVendor()

2024-03-15 03:39 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
建议先了解一下这个模型的需求

2024-03-15 03:41 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
不要教条主义。有些东西确实需要有确定的顺序，全局变量的析构和构造在不同编译单元里确实会不确定。但是有些地方我确实对这个顺序不care,为什么还要把一个简单的问题搞复杂了

2024-03-15 03:56 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
不用考虑运行时修改这么复杂的， 最多到 加载时 按需初始化

2024-03-15 10:07 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
这个跟线程安全关系不大

2024-03-15 10:24 UTC, yangbofun approved these changes

2024-03-18 03:04 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/allocator/DIPUCachingAllocator.h
> +  virtual size_t roundBytes(size_t nbytes) const {
全局变量初始化就是将来的坑，一个坑能找好几天

2024-03-18 03:05 UTC, lljbash approved these changes

2024-03-18 08:10 UTC, merged