zq/add switch env for autocompare
DeepLink-org/deeplink.framework pull request #749
Opened 2024-03-26 02:47 UTC by NeosZhang

add switch env for autocompare

2024-03-28 08:52 UTC, yangbofun commented on dipu/scripts/autogen_diopi_wrapper/auto_gen_code.sh
> +GENERATED_KERNELS=${DIPU_DIR}/torch_dipu/csrc_dipu/aten/ops/AutoGenedKernels.cpp
写相对路径。

2024-03-28 08:55 UTC, yangbofun commented on dipu/scripts/autogen_diopi_wrapper/auto_gen_code.sh
> +    PYTHON_CMD="$PYTHON_CMD --convert_config=${GENERATED_KERNELS_VENDOR}"
这里的--convert_config和上面的PYTHON_CMD里面的--参数可以写在一起。

2024-03-28 11:46 UTC, lljbash approved these changes

2024-03-28 11:46 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/auto_gen_code.sh
名字有点怪

2024-03-28 11:48 UTC, lljbash requested changes

2024-03-28 11:48 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/CMakeLists.txt
> -  WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
这里去掉了，是不是增量编译坏了？

2024-03-29 04:46 UTC, yangbofun commented on dipu/torch_dipu/csrc_dipu/CMakeLists.txt
> +  COMMENT "Generating ${GENERATED_KERNELS}$<$<BOOL:${GENERATED_KERNELS_VENDOR}>: with ${GENERATED_KERNELS_VENDOR}>"
这里加上DEPENDS.

2024-03-29 04:51 UTC, yangbofun commented on dipu/scripts/autogen_diopi_wrapper/auto_gen_code.sh
改成bash后，在cmake中这关于这条命令已经用不到python了，在bash脚本中，根据环境中的python来生成代码。如果环境没source好，就编译dipu，出现编译报错应该是正常行为。

2024-04-02 03:28 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/CMakeLists.txt
>      "${GENERATED_KERNELS_CONFIG}"
```suggestion
    "${GENERATED_KERNELS_SCRIPT}"
    "${GENERATED_KERNELS_CONFIG}"
    "${AUTOGEN_CODE_SH}"
```

2024-04-02 04:05 UTC, fandaoyi commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +            code += f'if (({inputs[i]}.data_ptr()) == {return_names[0]}.data_ptr())\n\t std::cout << "autocompare:\t{op_name}\t{inputs[i]}: " << std::endl << allclose_autocompare(result_cpu, {inputs[
这块 clang tidy 会有问题。Statement should be inside braces。

2024-04-02 04:43 UTC, fandaoyi commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +            code += f'if (({inputs[i]}.data_ptr()) == {return_names[0]}.data_ptr())\n\t std::cout << "autocompare:\t{op_name}\t{inputs[i]}: " << std::endl << allclose_autocompare(result_cpu, {inputs[
我也有个疑问， 为啥原来的代码要比较 inputs[i]}_cpu 和 {inputs[i]}？   inputs[i]}_cpu 如果没被修改，它就是我们自己 copy过来的， 所以就应该相等（如果copy 有问题那是另一个问题）？  如果 被修改了，前面不是已经比较过 result_cpu, result_device 了吗？

2024-04-02 05:13 UTC, yangbofun commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +        if len(return_names) == 1 and ("_out" in op_name or ".out" in op_name):
在上面判断self 和out是否是同一个tensor，如果是，out_cpu = self_cpu，而不是out_cpu 是self_cpu copy版本。然后这里的代码可以不用动。

2024-04-02 09:29 UTC, lljbash approved these changes

2024-04-08 06:53 UTC, NeosZhang commented
<img width="829" alt="image" src="https://github.com/DeepLink-org/deeplink.framework/assets/100055343/678738a8-030d-4dfc-8d84-702e27a46478">
以dipu_add_out_autocompare为例，生成的代码如图所示，当self或other的data_ptr等于out时，self_cpu = out_cpu或other_cpu = out_cpu，保证在torch.add(a, b, out=a)之类的调用时，autocompare的判断正确

2024-04-08 07:50 UTC, yangbofun approved these changes

2024-04-08 08:01 UTC, merged