[DICP][Ascend] Support llama2 7B with lightllm.
DeepLink-org/deeplink.framework pull request #787
Opened 2024-04-19 07:29 UTC by Reinerzhou

1. add pattern match;
2. add some ext_ops.

2024-04-21 16:25 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +        return torch.empty(idx_shape, dtype=x_dtype, memory_format=get_memory_format(x))
这个shape计算是不是某种特殊情况？

2024-04-21 16:29 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/codegen/graph_utils.h
> +        // {AscendString(ge::ir_option::PRECISION_MODE_V2), "fp16"},
这个地方最终哪种precision mode？

2024-04-22 02:25 UTC, tangzhiyi11 commented on dicp/dicp/dynamo_bridge/decompositions.py
> +    return aten.sum.dim_IntList(cond, dim=dim, keepdim=False, dtype=torch.int64)
dicp都可以用，是通用的。不过目前这个decompose实际没有用到，倒不是必须要加上的

2024-04-22 02:25 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +        allocated_output_with_offset = {}
allocated_output_with_offset 相关的都不需要，可以去掉

2024-04-22 02:25 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +
多个空行

2024-04-22 02:25 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/fusion_switch.cfg
> +            "ALL":"off"
{
    "Switch":{
        "GraphFusion":{
            "ALL":"on"
        },
        "UBFusion":{
            "ALL":"on"
         }
    }
}
用这个配置跑下看看

2024-04-22 02:25 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +            allocated_output_with_offset_tensor = None
allocated_output_with_offset 相关的都去掉

2024-04-22 02:25 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +        with record_function(f'load_and_run_run_{self.model_id}'):
这里不需要单独的record function

2024-04-22 02:25 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +        return self.exe.run(images, dims, output_shape, out_stride, out_storage_offset, allocated_output, allocated_with_offset_output)
allocated_with_offset_output 去掉

2024-04-22 02:25 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/opset_convert.py
> +            elif type(n.target) == InplaceCopyWithOffset:
这里也要去掉

2024-04-22 08:41 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +        return x
已改。

2024-04-22 08:42 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +        return torch.empty(idx_shape, dtype=x_dtype, memory_format=get_memory_format(x))
@tangzhiyi11

2024-04-22 08:43 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/codegen/fusion_switch.cfg
> +            "ALL":"off"
已改。

2024-04-22 08:44 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/codegen/graph_utils.h
> +        // {AscendString(ge::ir_option::PRECISION_MODE_V2), "fp16"},
继续保留原有的allow_fp32_to_fp16，其他两种在ci时存在部分算子精度问题。

2024-04-22 08:44 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +        allocated_output_with_offset = {}
已去掉。

2024-04-22 08:45 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +
flake8要求，检查后没问题。

2024-04-22 08:46 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +        with record_function(f'load_and_run_run_{self.model_id}'):
已去除。

2024-04-22 08:46 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +        return self.exe.run(images, dims, output_shape, out_stride, out_storage_offset, allocated_output, allocated_with_offset_output)
已去除。

2024-04-22 08:46 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/opset_convert.py
> +            elif type(n.target) == InplaceCopyWithOffset:
已去除。

2024-04-22 08:47 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +        return torch.empty(idx_shape, dtype=x_dtype, memory_format=get_memory_format(x))
嗯，是特殊情况

2024-04-23 03:46 UTC, jinminxi104 requested changes

2024-04-23 03:46 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +        return torch.empty(idx_shape, dtype=x_dtype, memory_format=get_memory_format(x))
需要完善这个逻辑，或者assert不支持的情况

2024-04-23 03:46 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        #     index = self.get_const_proxy(index, torch.int32)
删除

2024-04-23 03:46 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +    def flash_attention_inference(self, q, all_k, all_v, current_len, max_len):
这个代码是训练的那个fa吗？有经过测试吗？没有经过测试的话，写个comment

2024-04-23 03:46 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/pattern_replacement.py
> +class FuseLightLLMRmsNorm(BackendPatternBase):
是否在使用，是否经过测试？
如果经过测试的话，可以先放在这里

2024-04-23 06:00 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +    def flash_attention_inference(self, q, all_k, all_v, current_len, max_len):
是训练所用的fa，有经过测试；这个pr后会把所有自己注册的lightllm  op统一推个测试代码。

2024-04-23 08:15 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        #     index = self.get_const_proxy(index, torch.int32)
done。

2024-04-23 11:07 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/pattern_replacement.py
> +class FuseLightLLMRmsNorm(BackendPatternBase):
经知毅确认，此处未使用，已经先删掉，代码已备份。

2024-04-23 11:09 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        #     index = self.get_const_proxy(index, torch.int32)
gather的问题经知毅确认，此处未使用，已经先删掉，代码已备份留后续完善。

2024-04-23 11:09 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/codegen/load_and_run.py
> +            allocated_output_with_offset_tensor = None
已去除。

2024-04-23 11:10 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +        return torch.empty(idx_shape, dtype=x_dtype, memory_format=get_memory_format(x))
gather的问题经知毅确认，此处未使用，已经先删掉，代码已备份留后续完善。

2024-04-23 11:10 UTC, Reinerzhou commented on dicp/dicp/vendor/AscendGraph/ascend_op.py
> +        return torch.empty(idx_shape, dtype=x_dtype, memory_format=get_memory_format(x))
gather的问题经知毅确认，此处未使用，已经先删掉，代码已备份留后续完善。

2024-04-25 07:00 UTC, tangzhiyi11 approved these changes

2024-04-25 08:23 UTC, jinminxi104 approved these changes

2024-04-25 08:23 UTC, merged