[DIPU] DIPU migrate tool
DeepLink-org/deeplink.framework pull request #788
Opened 2024-04-22 03:32 UTC by CoolKbh

2024-04-22 03:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DeepLink-org/deeplink.framework?pullRequest=788) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DeepLink-org/deeplink.framework?pullRequest=788) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DeepLink-org/deeplink.framework?pullRequest=788) it.</sub>

2024-04-22 03:50 UTC, lljbash requested changes
先改这些

2024-04-22 03:50 UTC, lljbash commented on dipu/dipu_init.sh
> +echo "DIPU has loaded successfull !!"
```suggestion
echo "xxx is modified so that dipu will be automatically loaded when python starts"
```

2024-04-22 03:50 UTC, lljbash commented on dipu/dipu_deinit.sh
> +echo "Python environment has restored !!"
ditto，说下发生了什么事情，哪个文件被删掉了或者还原了

2024-04-22 03:50 UTC, lljbash commented on dipu/dipu_init.sh
> +echo "# <<< DIPU Initialize <<<" >> $sitecustomize_path
用 cat >> $sitecustomize_path << EOF

2024-04-22 03:50 UTC, lljbash commented on dipu/dipu_init.sh
> +export EN_DIPU=1
这个是没有道理的，因为用户不会每次启动这个脚本，甚至不应该用 source

2024-04-22 03:50 UTC, lljbash commented on dipu/dipu_init.sh
> +export EN_DIPU=1
考虑非法输入。实际上最好是看到 0 是 off，其他都是 on

2024-04-22 03:50 UTC, lljbash commented on dipu/dipu_deinit.sh
> +sitecustomize_path=${python_path}/sitecustomize.py
考虑到重复代码，二合一脚本是合理的

加上 usage help，和脚本头注释

文件末尾需要有换行

考虑加上可执行权限

2024-04-22 03:50 UTC, lljbash commented on dipu/dipu_init.sh
> +sitecustomize_path=${python_path}/sitecustomize.py
检查错误返回

考虑空格的存在

2024-04-23 06:52 UTC, CoolKbh commented on dipu/dipu_init.sh
> +echo "DIPU has loaded successfull !!"
done

2024-04-23 06:52 UTC, CoolKbh commented on dipu/dipu_deinit.sh
> +echo "Python environment has restored !!"
done

2024-04-23 06:54 UTC, CoolKbh commented on dipu/dipu_init.sh
> +echo "# <<< DIPU Initialize <<<" >> $sitecustomize_path
done

2024-04-23 06:54 UTC, CoolKbh commented on dipu/dipu_init.sh
> +export EN_DIPU=1
done

2024-04-23 06:56 UTC, CoolKbh commented on dipu/dipu_deinit.sh
> +sitecustomize_path=${python_path}/sitecustomize.py
done

2024-04-23 07:00 UTC, CoolKbh commented on dipu/dipu_init.sh
> +sitecustomize_path=${python_path}/sitecustomize.py
done

2024-04-23 08:19 UTC, lljbash reviewed
末尾要有 newline

还是有很多地方有变量带空格分词的隐患，建议用 shellcheck 查一下

2024-04-23 08:19 UTC, lljbash commented on dipu/dipu_envs.sh
> +chmod 755 dipu_envs.sh
提交时候加上就好，这里不用

2024-04-23 08:19 UTC, lljbash commented on dipu/dipu_envs.sh
> +fi
init 和 deinit 搞成两个函数，switch case，参考 build script 等

2024-04-23 10:47 UTC, lljbash approved these changes
我帮你改了，你看下改动，顺便测下 1424 上无权限状态的报错是否正常

2024-04-23 11:39 UTC, mrdanielw reviewed
这个功能需要在哪readme说明下吧？ 可以问问余悦？

2024-04-24 01:15 UTC, yewentao256 approved these changes

2024-04-29 03:53 UTC, lljbash commented
> 这个功能需要在哪readme说明下吧？ 可以问问余悦？

合完她会加

2024-04-29 04:20 UTC, merged