[WIP][dicp][ascend] Optimization for dynamic shape code logic.
DeepLink-org/deeplink.framework pull request #791
Opened 2024-04-24 07:08 UTC by pdx1989

Optimize dynamic shape handling:
1. Adjust relationship between SymInt and InputArgs.
2. Refine variable replacement in in/out shape structure.

2024-05-14 08:42 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +    @staticmethod
新增的算子，尽量都把单测带上

2024-05-14 11:12 UTC, jinminxi104 requested changes

2024-05-14 11:41 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +    def preprocess_expression(self, expr):
这个和后面一些处理动态shape的函数都和这个类无关，放到util里面

2024-05-14 11:54 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if isinstance(head, torch.SymInt):
去除hint

2024-05-15 06:57 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        split_size = self.get_proxy(ascend_op.Squeeze, (split_size, [0]))
self.get_proxy(ascend_op.Squeeze, (split_size, [0]))
这里传入的 split_size 是个int值，会有问题吧？

2024-05-15 08:26 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        return self.get_proxy(ascend_op.SplitToSequence, (x, dim, split_size))
执行路径已切分

2024-05-15 08:27 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        return self.get_proxy(ascend_op.Expand, (x, shape))
这里跟动态形状没有关系，原来的设计ExpandD和Expand两条路可以合并着写

2024-05-15 08:27 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        dim_const = self.get_const_proxy(dim, torch.int32)
是的，不影响执行逻辑

2024-05-15 08:33 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +                y = self.get_proxy(ascend_op.Cast, (y, get_ascend_dtype(x_dtype)))
是的，存在x/y数据类型不统一的情况

2024-05-15 08:42 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        src = self.get_proxy(ascend_op.Cast, (src, get_ascend_dtype(torch.float)))
类似下面这样：

```
    @register_conversion(torch.ops.lightllm.copy_with_offset.default)
    def copy_with_offset(self, x, src, start_dim, end_dim):
        if isinstance(start_dim, int) and isinstance(end_dim, int):
            dims = [x for x in range(start_dim, end_dim)]
            dims = self.get_const_proxy(dims, torch.int32, target_shape=[len(dims), 1])
            return self.get_proxy(ascend_op.ScatterNdUpdate, (x, dims, src))

        step = self.get_const_proxy(1, torch.int32)
        if isinstance(start_dim, int):
            start_dim = self.get_const_proxy(start_dim, torch.int32)
        if isinstance(end_dim, int):
            end_dim = self.get_const_proxy(end_dim, torch.int32)
        dims = self.get_proxy(ascend_op.Range, (start_dim, end_dim, step))
        dims = self.get_proxy(ascend_op.Unsqueeze, (dims, [-1]))
        return self.get_proxy(ascend_op.ScatterNdUpdate, (x, dims, src))
```

2024-05-15 08:55 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        src = self.get_proxy(ascend_op.Cast, (src, get_ascend_dtype(torch.float)))
修改了

2024-05-15 12:21 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        src = self.get_proxy(ascend_op.Cast, (src, get_ascend_dtype(torch.float)))
合并了，x/src是调试阶段的逻辑已删除

2024-05-16 01:10 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        split_size = self.get_proxy(ascend_op.Squeeze, (split_size, [0]))
<img width="819" alt="企业微信截图_17158217108334" src="https://github.com/DeepLink-org/deeplink.framework/assets/4810833/9cf74ccb-1f89-47f0-9585-77272d56f3e4">
是tensor，把它缩减成scalar，否则split会走tensor那边的逻辑

2024-05-16 01:40 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        split_size = self.get_proxy(ascend_op.Squeeze, (split_size, [0]))
添加了const proxy

2024-05-16 06:37 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if not 'split_to_sequence' in str(x):
<img width="712" alt="企业微信截图_1715841373761" src="https://github.com/DeepLink-org/deeplink.framework/assets/4810833/9f812aea-2d6f-49d9-b084-eb19bfd73cf0">
这边的算子名称包含split_to_sequence

2024-05-16 07:05 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +    def preprocess_expression(self, expr):
可以抽出来的函数都挪进去了

2024-05-16 07:06 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +            # x, y = self.promote_dtype(x, y, target_dtype=out_dtype)
满足需求，已经改回原来的写法

2024-05-16 10:37 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if isinstance(head, torch.SymInt):
已规范化head/dim固定常数的传入

2024-05-16 11:31 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +            start = start if start >= 0 else x_shape[dim] + start
暂时没有发现start为proxy的例子，已取消这边条件判断

2024-05-17 03:16 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/codegen/ascend.py
> +    @staticmethod
已经都加上了

2024-05-17 03:37 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if not 'split_to_sequence' in str(x):
这里对应的 aten ir是什么样子的？感觉根据名字来判断是否需要 split 有点太 tricky 了

2024-05-17 03:37 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        q = self.get_proxy(ascend_op.Cast, (q, get_ascend_dtype(torch.float16)))
这里为什么需要转成 float16?

2024-05-17 03:40 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if not 'split_to_sequence' in str(x):
Aten的IR贴一下看看

2024-05-17 03:41 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if not 'split_to_sequence' in str(x):
ascendIR已经是你改过的了，我无法判断

2024-05-17 06:05 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        return self.get_proxy(ascend_op.Expand, (x, shape))
已经退回原来的写法

2024-05-17 06:05 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        dim_const = self.get_const_proxy(dim, torch.int32)
已退回原来的写法

2024-05-17 06:10 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +            cast_op = self.get_proxy(ascend_op.Cast, (scalar_op, dtype))
这些比较的binary都用promote，然后再比较，现在的逻辑下，原本都是int的，也被cast成float

2024-05-17 06:11 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +                y = self.get_proxy(ascend_op.Cast, (y, get_ascend_dtype(x_dtype)))
同上，这些比较的binary都用promote，然后比较

2024-05-17 06:17 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +            start = start if start >= 0 else x_shape[dim] + start
现行dynamo下应该不会出现

2024-05-17 06:17 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        src = self.get_proxy(ascend_op.Cast, (src, get_ascend_dtype(torch.float)))
@tangzhiyi11 看下这个，你这边resolve吧

2024-05-17 07:02 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if not 'split_to_sequence' in str(x):
![企业微信截图_1715928007467](https://github.com/DeepLink-org/deeplink.framework/assets/4810833/3c1fddd6-4a07-40ca-8109-52f632bdd275)

aten ir是这样的

2024-05-17 07:26 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        q = self.get_proxy(ascend_op.Cast, (q, get_ascend_dtype(torch.float16)))
![企业微信截图_17159306829457](https://github.com/DeepLink-org/deeplink.framework/assets/4810833/536ff3c0-3f2b-4e12-a3d6-653911273210)
910上面也会报错

2024-05-17 08:54 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +            cast_op = self.get_proxy(ascend_op.Cast, (scalar_op, dtype))
好的

2024-05-17 08:54 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +                y = self.get_proxy(ascend_op.Cast, (y, get_ascend_dtype(x_dtype)))
已修改

2024-05-17 09:04 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        if not 'split_to_sequence' in str(x):
已通过meta属性获取num_split，取消SplitToSequence路径

2024-05-21 03:27 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        q = self.get_proxy(ascend_op.Cast, (q, get_ascend_dtype(torch.float16)))
这里做个判断吧，如果q是float的，这里转成 fp16，返回的时候，fa再转回到float

2024-05-22 02:56 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +            cast_op = self.get_proxy(ascend_op.Cast, (scalar_op, dtype))
这个地方还需要修改

2024-05-22 03:05 UTC, jinminxi104 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +                y = self.get_proxy(ascend_op.Cast, (y, get_ascend_dtype(x_dtype)))
和gtscalar一样，逻辑依然有问题

2024-05-22 07:20 UTC, tangzhiyi11 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +            y_shape) or not_all_num_shape(out)
这里可以试试改成下面这样，我觉得应该可以不用关心 x/y 的 shape

    @register_conversion([aten.lt.Scalar, aten.lt.Tensor])
    def lt(self, x, y):
        if not isinstance(y, torch.fx.proxy.Proxy):
            x_dtype = x.node.meta['val'].dtype
            y = self.get_const_proxy(y, x_dtype)
        return self.get_proxy(ascend_op.Less, (x, y))

2024-05-23 07:42 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +            y_shape) or not_all_num_shape(out)
可以这样改

2024-05-23 07:42 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +        q = self.get_proxy(ascend_op.Cast, (q, get_ascend_dtype(torch.float16)))
已添加

2024-05-23 08:24 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +            y_shape) or not_all_num_shape(out)
这样改，llama hf的动态形状会有问题

2024-05-23 08:25 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +            cast_op = self.get_proxy(ascend_op.Cast, (scalar_op, dtype))
加入了对齐类型优先级的逻辑

2024-05-23 08:25 UTC, pdx1989 commented on dicp/dicp/vendor/AscendGraph/conversion.py
> +                y = self.get_proxy(ascend_op.Cast, (y, get_ascend_dtype(x_dtype)))
加入了类型优先级的逻辑

2024-05-23 11:14 UTC, tangzhiyi11 approved these changes

2024-05-29 06:17 UTC, jinminxi104 approved these changes

2024-05-29 06:33 UTC, merged