support muliti cards in one process
DeepLink-org/deeplink.framework pull request #795
Opened 2024-04-26 05:49 UTC by zhaoguochun1995

![截屏2024-04-26 下午1 37 27](https://github.com/DeepLink-org/deeplink.framework/assets/109069909/47a9c02e-890e-4c55-8c9e-697c7fbdf2e2)

2024-04-28 06:15 UTC, caikun-pjlab reviewed
需要补充一下多卡的测例

2024-04-28 06:15 UTC, caikun-pjlab commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
> +    int32_t canAccessPeer = 0;
这个地方可以参考torch_npu的torch_npu/csrc/core/npu/NPUPeerToPeerAccess.h，加个cache，不用每次device之间的拷贝都判断是否支持peer access，并enable

2024-05-16 02:54 UTC, lljbash requested changes

2024-05-16 02:54 UTC, lljbash commented on dipu/tests/python/unittests/test_multi_thread.py
unittest 目录下不能放这种非标测试

放到 individual 里

2024-05-16 02:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +thread_local deviceId_t kCurrentDevice = -1;
不是常量，不要用常量命名规则，引起误解

2024-05-16 02:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +  static int deviceCount = getDeviceCount();
const?

2024-05-16 02:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
> +thread_local AscendDeviceId kCurrentDevice = kDeviceIdUninit;
ditto，k+驼峰是常量专属

2024-05-16 02:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
> +thread_local AscendDeviceId kCurrentDevice = kDeviceIdUninit;
看完代码，没有发现 default 要变的必要

2024-05-16 02:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
>  }
这段非常难懂。

首先，如果允许有意义的 <0 参数，应当注释加以说明其意义

其次除了未初始化的情况，还有什么情况会导致 default 和 current 不一样呢？uninit 应当单拿出来显得更清晰吧，default 也不用动

最后，这里似乎完全没有线程安全的考量了。

2024-05-16 02:54 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
> +  std::shared_ptr<void> hostBufferUnique(hostBuffer,
这里用 shared 是不是太重了，只是想要一个 scope guard 而已

2024-05-16 03:52 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
这个也不需要，除了你们后加的 pin 和 recordstream， 这个文件里其他的的应该都处理过 guard了， 没加的就是不需要的，

2024-05-16 03:52 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
其他的也检查下 pytorch的逻辑。

2024-05-16 03:52 UTC, fandaoyi commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +    tensors = re.findall("Tensor +[\w\d_]+", fun_config["schema"]) + re.findall(
备注下：类cuda的无需加 guard， 可优化

2024-05-16 03:52 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +    c10::DeviceGuard guard(src.device());
备注下： 这个 guard 放到这里太底层了， 这个类后面要重构下了，把策略拆出来。另外 参考下 cuda的逻辑， d2OtherD 和 d2Self 可能要分开处理， cuda 的 D2Other 有额外的同步。建议后面再单独梳理下这个类 。 可以挂我这里

2024-05-16 03:52 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
> +  if (kCurrentDevice == kDeviceIdUninit) {
每个新线程第一次调用setDevice 都会修改  kDeviceIdDefault， 并可能影响随后线程的 currentDevice @jfxu-st  @yangbofun  你们确定这个行为是预期的？

2024-05-16 03:52 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
> +    setDevice(kDeviceIdDefault);
如果kDeviceIdDefault 不是0, 打印个 warnning吧。 至少知道设置了一个 被修改的 kDeviceIdDefault

2024-05-16 03:53 UTC, fandaoyi commented
> 需要补充一下多卡的测例

多卡测例需要改 ci， 可以考虑另外放个 pr 处理？

2024-05-16 04:31 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
> +  if (kCurrentDevice == kDeviceIdUninit) {
按照这个逻辑， 其实是 每个新线程如果没有显式设置自己的 device， 需要返回系统上一次设置的 device作为自己的默认device （而不是0）。 把名字kDeviceIdDefault 改成 LastSetDevice  或者其他含义更明确的名称 是否更有意义。

2024-05-16 04:35 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
> +  if (kCurrentDevice == kDeviceIdUninit) {
我之前在 kestrel 项目 时，遇到过另一个问题： 某设备是  main thread set了device， 其他线程默认就要是 main thread 的 device。   我不确定华为期待的 新线程的 默认 device  究竟是是 整个进程的 LastSetDevice， 还是 MainThreadCurrentDevice。

2024-05-16 04:48 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
>  }
很难懂。名字肯定得改下，process_last_set_device 和 thread_current_device 之类的，还需要注释。

2024-05-16 04:57 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +    setDevice(0);
这里不调用 底层的 devapi::current_device 了？ 那 ascend 里面的 那个一大堆逻辑的 current_device 其实不会被调到， 这是预期的行为吗？   还有这样其他地方的 setDevice 我们无法捕捉到了。

2024-05-16 05:01 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +    devId = devapis::current_device();
我感觉这一层其实不会出现 -1, 即使设置 -1 的 c10：device 时，上层就调用 currentDevice处理掉了。

2024-05-16 05:01 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/vendor/ascend/deviceimpl.cpp
> +thread_local AscendDeviceId kCurrentDevice = kDeviceIdUninit;
要的，不然会出现通信卡住的问题

2024-05-16 06:40 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
reshape 有可能访问设备？有可能copy

2024-05-16 06:45 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +    devId = devapis::current_device();
上层是指哪里？

2024-05-16 06:45 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +    devId = devapis::current_device();
上层如果漏了呢？

2024-05-16 06:48 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
device 应该加在统一的地方，比如wrapper开头的地方，最好是直接注册的函数那里加，里面就别加了。不然有的加在里面，有的又加在外面。

2024-05-16 06:50 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
resize_里面没有加

2024-05-16 07:14 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +  DIPUStream copy_stream = dipu::getCurrentDIPUStream(src_device.index());
原来的设计里， stream 同步不是在这一层控制的， 这是个基础函数。。这样改就完全乱了。。建议先最小化修改。

2024-05-16 07:45 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +    auto dstCurrentStream = dipu::getCurrentDIPUStream(dst_device.index());
这是个基础函数，不要在这一层处理流同步，放到 copyPreProcess， postProcess 处理，。

2024-05-16 07:46 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +    devId = devapis::current_device();
之前没有加device_gurad, 还有华为上，deviceimpl里面做了防御的。这里做个防御有什么问题？

2024-05-16 08:49 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
不会， 你对照pytorch cuda的看下， 这里都是调用的 native实现，和 cuda的都是一样的

2024-05-16 09:11 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +    auto dstCurrentStream = dipu::getCurrentDIPUStream(dst_device.index());
放到基类里面，所有继承了的地方都需要加上？

2024-05-16 09:13 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +    auto dstCurrentStream = dipu::getCurrentDIPUStream(dst_device.index());
这个就是copy_copy_d2d 函数特有的逻辑，放在外面更不易懂了呀

2024-05-16 11:32 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +    auto dstCurrentStream = dipu::getCurrentDIPUStream(dst_device.index());
这里就是个 mem copy，不做任何别的操作。 还有 这个同步是所有 tensor d2d copy 需要做的， 不只是  mem copy ， 只不过你这个pr 没重写 copyNodirectBetweenDevices， 那里还是基于cpu中转的。

2024-05-16 11:33 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +    auto dstCurrentStream = dipu::getCurrentDIPUStream(dst_device.index());
最初期望的是 子类最好是只处理自己需要处理的，剩下的调回基类。   只不过现在几个子类都没调用 基类的实现，那就把这个做成2个工具函数，子类调用下也可以。 这块后面我打算拆成策略类。

2024-05-16 11:42 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +    srcEvent.record(stream);
在自己的 record  个 event， 再在自己的流上等待没意义的。

2024-05-17 02:38 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
> +    srcEvent.record(stream);
实践下来，确实是这样的。pytorch是这样写的，有点纳闷

2024-05-17 03:31 UTC, zhaoguochun1995 commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +    tensors = re.findall("Tensor +[\w\d_]+", fun_config["schema"]) + re.findall(
这块做成可配置的了。可以配置是否生成device guard code了

2024-05-17 03:39 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +    devId = devapis::current_device();
我建议这里想防御应该用 assert 的形式，把问题暴露出来，而不是藏起来

2024-05-17 06:11 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +      setDevice(lastDevice);
Because on some software stacks, getDevice is not allowed to be called before setDevice is called. So we do this。 在国产软件你踩的坑不够多，踩多了就不会这么想了

2024-05-17 06:11 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +      setDevice(lastDevice);
加了个注释

2024-05-17 06:42 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/deviceproxy.cpp
> +      setDevice(lastDevice);
曾经出现过很多次和这里没做处理相关的bug。上层的调用方式千奇百怪

2024-05-21 04:11 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
里面 _resize_impl_dipu_ 有加, 放到里面是因为 并非所有case 都需要 guard,   上面写 comment了.  你要愿意在这里加 就把里面的删掉吧.

2024-05-21 04:11 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
这个哪里都不需要加.对照下 torch的逻辑

2024-05-22 02:47 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
那需要把RecordBlockCreator 删掉，不然RecordBlockCreator 会出问题

2024-05-22 03:04 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
device_guard 挪到RecordBlockCreator上面了，为了保证record不出错

2024-05-22 03:06 UTC, zhaoguochun1995 commented on dipu/torch_dipu/csrc_dipu/aten/RegisterDIPU.cpp
> +  const OptionalDeviceGuard device_guard(device_of(self));
RecordBlockCreator 需要devcie_guard。

2024-05-22 09:24 UTC, yangbofun commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
>                           bool isSynchronousCopy) {
我记得D2D里面会有p2p，p2p时会用到是否同步。

2024-05-22 09:25 UTC, yangbofun commented on dipu/torch_dipu/csrc_dipu/aten/ops/DIPUCopy.hpp
>                           bool isSynchronousCopy) {
> 对D2D来说，`isSynchronousCopy` 这个参数不会用到的话，可以从函数签名中去掉？
我记得D2D里面会有p2p，p2p时会用到是否同步。

2024-05-23 08:37 UTC, fandaoyi approved these changes

2024-05-31 07:50 UTC, caikun-pjlab approved these changes

2024-06-03 03:06 UTC, mrdanielw approved these changes

2024-06-03 03:08 UTC, lljbash reviewed
nop

2024-06-03 03:08 UTC, lljbash approved these changes

2024-06-03 03:23 UTC, merged