add get comm name
DeepLink-org/deeplink.framework pull request #798
Opened 2024-04-28 07:36 UTC by tangzhiyi11

2024-05-30 06:21 UTC, caikun-pjlab approved these changes

2024-06-03 03:15 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.cpp
> +  const auto localCommsKey = getDeviceIds(devices);
dicl p2p 通信时使用的 comm 是单独的,这样获取的只是 collective 的 comm.  不知道你们拿这个 name是要做啥?  这是不是你们期待的行为.

2024-06-03 03:15 UTC, fandaoyi commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.cpp
> +  return devapis::diclGetCommName(commName, comm);
判断下弱符号是否存在,不存在最好能有个明确的报错. 要不会报段错误

2024-06-03 06:48 UTC, lljbash requested changes

2024-06-03 06:48 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/DICLUtils.hpp
> +constexpr const int MAX_COMM_NAME_LENGTH = 128;
这个来源是什么？建议和华为的人对一下，我发现这串调用有缓冲区溢出风险，没有任何保护。

2024-06-03 06:48 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/DICLUtils.hpp
> +
这里会被调用多次吗？一个 lazy initialization 或许更合适？

2024-06-03 06:48 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.h
> +  // NOLINTNEXTLINE(readability-const-return-type) just follow parent class.
没理解这行，下面返回值不是 const 呀

2024-06-03 06:48 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.h
> +  std::string getCommName(at::DeviceIndex device_index);
```suggestion
  std::string getCommName(at::DeviceIndex device_index) const;
```
整串调用都可以加上 const，包括 py 层参数

2024-06-03 09:18 UTC, tangzhiyi11 commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.cpp
> +  const auto localCommsKey = getDeviceIds(devices);
![image](https://github.com/DeepLink-org/deeplink.framework/assets/5955111/b467c64b-3c9b-4a80-af0e-e7cc46b1f87e)
使用场景是图上用的通信算子，需要获取当前通信域的名称来作为参数。

2024-06-03 09:18 UTC, tangzhiyi11 commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.cpp
> +  return devapis::diclGetCommName(commName, comm);
好的

2024-06-03 09:21 UTC, tangzhiyi11 commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/DICLUtils.hpp
> +constexpr const int MAX_COMM_NAME_LENGTH = 128;
![image](https://github.com/DeepLink-org/deeplink.framework/assets/5955111/02179667-a12f-426f-8132-62a0b0eae18d)
https://github.com/Ascend/pytorch/blob/e6b862b56ce59d480b15298c69826f9771101bb1/torch_npu/csrc/distributed/ProcessGroupHCCL.cpp#L44
这个是我看torch_npu里定义的长度，倒是没有找到文档上明确提过这个大小，我再跟华为人确认下

2024-06-03 10:43 UTC, tangzhiyi11 commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/ProcessGroupDICL.h
> +  std::string getCommName(at::DeviceIndex device_index);
getCommName 里调用了 getDICLComms，应该不能是 const 的

2024-06-04 08:40 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/DICLUtils.hpp
> +constexpr const int MAX_COMM_NAME_LENGTH = 128;
需要注意，这个并不是华为专用的接口，而且缓冲区溢出是比较危险的

2024-06-04 08:47 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/DICLUtils.hpp
> +  std::string getName() {
要不要改为引用或者 string view，让调用者决定是否复制？

2024-06-04 11:02 UTC, tangzhiyi11 commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/DICLUtils.hpp
> +constexpr const int MAX_COMM_NAME_LENGTH = 128;
https://www.hiascend.com/forum/thread-0269152795052264057-1-1.html
问了华为的人，暂时也没有明确的文档记录，现在还是以torch_npu的代码为参考吧

2024-06-04 11:02 UTC, tangzhiyi11 commented on dipu/torch_dipu/csrc_dipu/runtime/distributed/DICLUtils.hpp
> +  std::string getName() {
好的

2024-06-05 08:25 UTC, lljbash approved these changes

2024-06-05 08:28 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.cpp
> +  return {};
需要明显的报错，你这样似乎是 return 了一个 success

2024-06-05 09:23 UTC, tangzhiyi11 commented on dipu/torch_dipu/csrc_dipu/runtime/devproxy/diclproxy.cpp
> +  return {};
好的

2024-06-06 02:40 UTC, merged