refactor(dipu): rename DIPUEvent::stream_id to last_recorded_stream_id
DeepLink-org/deeplink.framework pull request #812
Opened 2024-05-22 06:44 UTC by wiryls

将部分代码从以前的 PR #750 挪到这里，旧的 PR 现已 closed。
同时也按照 jf 之前的修改进行二次修改，主要是重命名 stream_id 的接口。

> 原本想新增一个 allocator 专用的 event 来着，但 allocator 那边各种各样的地方都在引用当前版本的 event，改造将会引起大量文件的变更，暂时先不动它们了。

2024-06-17 03:18 UTC, lljbash requested changes

2024-06-27 07:37 UTC, fandaoyi reviewed
我怎么感觉这个pr 有问题, 吴仪 你同步下最新的 代码 这比对不是新的.

2024-07-05 10:44 UTC, fandaoyi approved these changes

2024-07-25 08:07 UTC, lljbash approved these changes

2024-07-25 08:07 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/runtime/core/DIPUEvent.h
> + * DIPUEvent is lazily constructed while "record".
语法怪怪

2024-07-26 03:30 UTC, merged