[DIPU] Remove autogen check code
DeepLink-org/deeplink.framework pull request #858
Opened 2024-07-01 04:49 UTC by CoolKbh

2024-07-11 03:22 UTC, lljbash requested changes

2024-07-11 03:22 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +        )
重复代码太多，没法维护了

或许可以用一个 dict 维护一下，把通用的都合并了，调用的时候再**展开

2024-07-11 03:22 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +        if remove_check_code:
一样

2024-07-11 03:22 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/autogen_wrapped_code.sh
> +    --remove_check_code=False --fun_config_dict='{\"current_device\":\"${UsedVendor}\",\"current_torch_ver\":\"${Torch_VERSION}\"}'"
变成参数，在 cmake 里面用 option 控制

2024-08-02 06:07 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/CMakeLists.txt
> +set(AUTOGEN_CODE_REMOVE_CHECK False)
得留一个 option 让修改吧，然后判断 option 去传给 script

2024-08-05 09:33 UTC, CoolKbh commented on dipu/scripts/autogen_diopi_wrapper/autogen_wrapped_code.sh
> +    --remove_check_code=False --fun_config_dict='{\"current_device\":\"${UsedVendor}\",\"current_torch_ver\":\"${Torch_VERSION}\"}'"
done

2024-08-05 09:33 UTC, CoolKbh commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +        if remove_check_code:
done

2024-08-05 09:33 UTC, CoolKbh commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +        )
done

2024-08-07 07:51 UTC, lljbash approved these changes

2024-08-07 08:14 UTC, lljbash requested changes
不要叫 check code 了，里面有些功能不是 check。
或许可以叫 enable dipu extra feature
@wiryls 看看

2024-08-07 08:49 UTC, lljbash commented on dipu/torch_dipu/csrc_dipu/CMakeLists.txt
> +option(AUTOGEN_CHECK_CODE "Whether to generate check code for AutoGenedKernels" ON)
> 另外它本身就是个变量，直接替换掉这里的 `AUTOGEN_CODE_REMOVE_CHECK` 就行

不大行吧，python 不一定认得

2024-08-08 03:24 UTC, CoolKbh commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +            'dipu::profile::RecordBlockCreator dipuRecorder(R"({0})");\n'.format(
done

2024-08-08 07:09 UTC, CoolKbh commented on dipu/torch_dipu/csrc_dipu/CMakeLists.txt
> +option(AUTOGEN_CHECK_CODE "Whether to generate check code for AutoGenedKernels" ON)
done

2024-08-08 07:13 UTC, CoolKbh commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +        record_code_after_call_diopi += 'TORCH_CHECK(ret == ::diopiSuccess, __FILE__, ":", __LINE__, R"({0})", " error, error code is ", ret, "error message is ", diopiGetLastErrorString());\n'.forma
done

2024-08-08 08:32 UTC, lljbash requested changes

2024-08-08 08:32 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/diopi_wrapper_template.py
> +  $record_code_after_call_diopi
拆成两个
check ret 并不是 record，而是一个必须步骤

2024-08-08 08:32 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +        if not remove_extra_code:
这个判断还是到处都是
让它生成，然后 substitute 的参数一次判断调整好
像这种 custom_code_at_the_beginning 混了两个功能的，说明原本设计有问题，把它拆成两个占位符

2024-08-08 08:32 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/diopi_wrapper_template.py
上面有个  `dipu::profile::RecordBlockCreator _(__FUNCTION__);` 漏了

2024-08-08 08:57 UTC, CoolKbh commented on dipu/scripts/autogen_diopi_wrapper/diopi_wrapper_template.py
> +  $record_code_after_call_diopi
那我就把check ret放回template里吧

2024-08-08 09:02 UTC, CoolKbh commented on dipu/scripts/autogen_diopi_wrapper/diopi_wrapper_template.py
加上了

2024-08-08 09:42 UTC, CoolKbh commented on dipu/scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py
> +        if not remove_extra_code:
done

2024-08-08 09:58 UTC, lljbash approved these changes

2024-08-09 02:37 UTC, Wrench-Git approved these changes

2024-08-09 02:41 UTC, CoolKbh commented on dipu/scripts/autogen_diopi_wrapper/diopi_wrapper_template.py
> -  synchronizeIfEnable();
已经换掉了

2024-08-09 08:47 UTC, merged