feat fused_adamw
DeepLink-org/deeplink.framework pull request #938
Opened 2024-09-05 06:50 UTC by zyf654321

2024-09-06 02:57 UTC, lljbash requested changes
加上单元测试

2024-09-25 02:49 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
> +    }
削减重复代码，考虑：
1. 提取函数
2. 使用 std::transform

2024-09-25 02:50 UTC, lljbash commented on dipu/tests/python/unittests/test_adamw.py
> +    @onlyOn("CUDA")
如果期望所有芯片都实现，应该用 skipon 比较好

2024-10-09 06:29 UTC, lljbash commented on dipu/scripts/autogen_diopi_wrapper/diopi_functions.yaml
> +    }
toDiopiTensorHandleVector
已经有这个函数了

2024-10-11 06:43 UTC, lljbash approved these changes

2024-10-11 07:03 UTC, fandaoyi approved these changes

2024-10-11 07:05 UTC, merged